### ISSUE TITLE
lane markings do not respect original proportions for street with non-default length

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#102]
Some segment plane textures such as dotted line lane markings don't look correct when specifying a length other than the 150m default value.

Instead, the textures should all appear to be the same aspect ratio as they appear in the length property default value of 150m.

Here is a screenshot of a street of 33m length whose dashed striping lines appear as dots instead of longer dashed lines adjacent to the turn lanes.
![image](https://user-images.githubusercontent.com/470477/132264869-34904b99-78a7-4f96-85bd-641f8db62935.png)

The dashed white lines should be longer, here's how they would look at default scale
![image](https://user-images.githubusercontent.com/470477/132440714-3c6724e8-b7ea-4322-a315-ec67459b8652.png)

**Comment by Algorush** [comment]
Hi Kieran. Should white lines never look like dots?

**Comment by kfarr** [comment]
@Algorush correct, the length of the dashes, and other z repeating textures, should be the same as default length (no z scale value specified) or any manually specified length value

**Comment by gnansai** [comment]
Hi @kfarr Could you direct me to the road glb assets that are being used here?

**Comment by kfarr** [comment]
@Algorush thanks I merged https://github.com/3DStreet/3dstreet/pull/206

Next we should add similar support for other segment types like divider or other dashes. I can create a test scene to help make sure we're looking at the same thing

**Comment by Algorush** [comment]
> @Algorush thanks I merged #206
> 
> I can create a test scene to help make sure we're looking at the same thing
Hi, yes, please. A test scene with examples of the issues that need to be fixed would be very helpful. Or just give examples in the screenshots as it is now and how it should look

**Comment by kfarr** [comment]
Hi @algorush, here is an example streetmix scene to use for testing:
https://streetmix.net/kfarr/44/streetmix3d-all-segment-cases-test

When running 3dstreet locally, append it to the localhost path as follows if your port is 7001: 
http://localhost:7001/#https://streetmix.net/kfarr/44/streetmix3d-all-segment-cases-test

In index.html change line 72 from
`        <a-entity id="street-parent" street streetmix-loader set-loader-from-hash="defaultURL: https://streetmix.net/kfarr/3"></a-entity>`
to
`        <a-entity id="street-parent" street="length: 50" streetmix-loader set-loader-from-hash="defaultURL: https://streetmix.net/kfarr/3"></a-entity>`

You can then see which elements do not scale correctly when you compare 50m length to the default of 150m. Mostly they are other segment markings (other street markings) as well as road textures

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/pull/209
