### ISSUE TITLE
[Assets/Parsing] Add Pedestrians

### ISSUE THREAD

**Issue by pjstein** [3DStreet/3dstreet#106]
Streetmix scenes, like streets, often feature pedestrians, and 3d streets does not render pedestrians today. Let's change that!

There are human characters available [in the assets repo](https://github.com/3DStreet/3dstreet-assets/tree/main/sets). Teach 3DStreets how to pull these assets in with the `assets.js` file. Then, update the parser to pull in the pedestrian density of a sidewalk. Given the density, render some random number of random human characters along the sidewalk. 

In this revision, we need not animate the characters (or move them). Just lay things out to start and the rest can come.

**Comment by pjstein** [comment]
I'll be working on this one over the next couple weeks

**Comment by kfarr** [comment]
resolved with https://github.com/3DStreet/3dstreet/pull/112
