### ISSUE TITLE
Add cyclist and scooter 3D models to 3dstreet.

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#116]
glb should be ready to go https://github.com/3DStreet/3dstreet-assets/blob/main/sets/micro-mobility-devices/micro-mobility-devices_v01.glb

segments to support:
scooter
bike-lane

possible or future segments that could be supported? (might need scooter and bicycle versions without people)
scooter-drop-zone
sidewalk-bike-rack

open questions:
- Place just 1 at center like vehicle? Or dispersed along length of segment like pedestrians? Or something else?

**Comment by srothst1** [comment]
I will take a look at this shortly and open up a PR in [3dstreet](https://github.com/3DStreet/3dstreet).
