### ISSUE TITLE
Road to Zero Grant Application

### ISSUE THREAD

**Issue by srothst1** [3DStreet/3dstreet#120]
Here is more information on the Road to Zero Grant:
https://nsc.submittable.com/submit/208642/2022-road-to-zero-community-traffic-safety-grants

#### Please note that the application deadline is January 7th

**Comment by srothst1** [comment]
@kfarr please feel free to add more details and information.

**Comment by kfarr** [comment]
Today there was a helpful webinar on the program, the first presenter about 15 minutes in regarding Lorain Ohio seemed most relevant to a potential 3dstreet grant: https://nsc-org.zoom.us/rec/play/kDi68DGTXTvD6czUlnQxHu5CSVaE_5ZCZb_y4NFIhx1UPH3OnEbrgXaTZLrqhnLZKBS9ZXr1Cz0rAvJz.-j02H9fda4jESrEg?continueMode=true&_x_zm_rtaid=8lheMsASSpmJChSDkpY2mw.1638937328577.a5d6e94b0786c84f1c23ebc141464138&_x_zm_rhtaid=673

Here is an example application:
- https://nsc-org-storage.azureedge.net/cms/nsc.org/media/site-media/docs/safe-driving/road-to-zero/rtz-sample-grant-application.pdf

**Comment by srothst1** [comment]
@kfarr thank you for sharing a sample application. This is particularly helpful on my end. Some thoughts:
- It will likely take a significant amount of time to get this application together. To properly answer the prompts, we will need to have a very well-formulated plan. This will require at least a few internal discussions.
- The 12-month detailed project budget looks particularly challenging to put together. I usually think in terms of weeks (not months) :sweat_smile: 
- Any ideas for what would go in the ***Supporting Documentation*** section?

Overall, I see this as a really exciting opportunity! It's a great chance to get the funding necessary to showcase some real-world uses for 3dstreet. Hopefully, it will also provide funding for roadmap-related developer muscle.

**Comment by kfarr** [comment]
- find, list potential partners
- join road to zero as a member (done)
- create submittable account (done)
- read grant ask, outline key parts
- read [example grant](https://nsc-org-storage.azureedge.net/cms/nsc.org/media/site-media/docs/safe-driving/road-to-zero/rtz-sample-grant-application.pdf)

**Comment by kfarr** [comment]
Started 2 new docs:
- Notes on road to zero preso
- Applications

Links omitted as they contain private data contact me for access
