### ISSUE TITLE
add logo and "viewer" badge to github repo

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#134]

**Comment by kfarr** [comment]
another commit

![image](https://user-images.githubusercontent.com/470477/149876741-e2da1d09-4170-4fa5-8d59-f3087c82db02.png)

and mobile

![image](https://user-images.githubusercontent.com/470477/149876776-bb6f1e7c-aab8-4e2d-8a58-29b04e4e6dce.png)

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/commit/9243da40820f11e0398b2361b969f1b13b2f06ac

updated:
- longer text field, right justify
- button is big enough to actually click
- removed Thing on the Right

still to do:
- continue form input text field text styling to match figma
- continue button styling

**Comment by srothst1** [comment]
DONE:
- [ ] 3DStreet viewer text
  - [ ] Text formatted correctly
  - [ ] Link to website working
- [ ] Search bar
  - [ ] UI looks pretty close
  - [ ] updates scene on enter
TODO:
- [ ] Clean up code
  - [ ] No miscellaneous scripts in the html
  - [ ] Commented and consistent code
- [ ] Tune up three share buttons
  - [ ] Get glTF download working
  - [ ] Update CSS that positions buttons
  - [ ] Update hover state of buttons to match UI designs
- [ ] Fix search box
  - [ ] Size of search box should be dynamic
  - [ ] There should be a search icon to the right of the icon
NEXT:
- [ ] Camera switching widget

**Comment by kfarr** [comment]
done with #149 !
