### ISSUE TITLE
differentiate parking lanes

### ISSUE THREAD

**Issue by burritojustice** [3DStreet/3dstreet#142]
This is great. Have you considered making parking lanes a different color or paint treatment?

**Comment by kfarr** [comment]
Thanks! Yes we would definitely like to have support for better striping for parking segments.

Here is a link to our tracking sheet which highlights in yellow the 14 parking related Streetmix segment variants that are yet to be handled with proper striping:
https://docs.google.com/spreadsheets/d/1VGRxCEPN6w99BxHQoIeWVnZFDhAL4FB_JfhMOvQihxI/edit#gid=0&range=95:108

We already have the stencil art assets in ready-to-use atlas form, there are the "T" markers as well as "+" and a line of perpendicular markings:
https://github.com/3DStreet/3dstreet/blob/main/assets/materials/stencils-atlas_2048.png

The next step would be to add handling for these segment variants in the growing monster of if / else statements here:
https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L499

If you're interested in learning how to contribute, happy to work with you. @srothst1 has also added support for segment variants recently and could be a good mentor to get started.

**Comment by kfarr** [comment]
It would be possible to place vehicles in some or all of the parking spaces as well.

**Comment by kfarr** [comment]
First step is a merged PR to differentiate parking lanes (and flex lanes) with darker asphalt color:
https://github.com/3DStreet/3dstreet/pull/143

**Comment by kfarr** [comment]
fixed with https://github.com/3DStreet/3dstreet/pull/144
