### ISSUE TITLE
lost lane coloring in the last build

### ISSUE THREAD

**Issue by burritojustice** [3DStreet/3dstreet#145]
I think we lost the flex lane coloring we did in the PR before the parking symbol PR.

https://streetmix.net/burritojustice/16/

Also did we discuss lane markings for flex lanes?

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3979711/162284098-524f5b38-7fb8-440f-88de-39211b31f245.png">

**Comment by kfarr** [comment]
Good call, in the parking changes I removed surface-dark in favor of bright-lane which is intended to be concrete. We could make the flex zone segments the same as the new parking lanes? 

A few questions:
- what is a flex zone? it appears to be a loading zone for passenger pickup with either taxi or rideshare vehicles. only taxi is supported in 3dstreet at the moment
- what striping should it have? if it's a non-metered parking (passenger loading) zone it would white paint on the curb but no other striping (if adjacent to curb)
- if it's "floating" such as on the other side of a curbside parking protected bike lane, it has more complicated markings than would be currently supported by 3dstreet.
- a simple option is solid white lines on either side?

**Comment by burritojustice** [comment]
Good question -- it's parking-not-parking. Keep in mind I mainly used it so I could actually get a vehicle to show up in the lane. (I have a long-standing issue open in streetmix for either trucks in the flex zone, or to have a dedicated loading lane as an asset but there's been no movement on that in a year.)

White line at minimum though. 

While a FLEX stencil would just confuse people, LOADING is definitely a thing. But what asset would that go with?

https://rae-prostores.com/24-inch-loading-stencil.html

**Comment by kfarr** [comment]
So it seems like it's for loading / unloading of people and goods

> In between the two is the flexible space where people find their bus, park a car, hail a cab, drop off a passenger or make a delivery. Increasingly, this space ...
[Flex Zone/Curb Use Priorities in Seattle - Transportationhttp://www.seattle.gov › programs › parking-regulations](http://www.seattle.gov/transportation/projects-and-programs/programs/parking-program/parking-regulations/flex-zone/curb-use-priorities-in-seattle)

So then maybe the lighter concrete color, white lines on either side, stencils that say:
ONLY
LOADING
in similar fashion to other repeated stencils?

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/commit/4fa43b1066feda66e4bec575bc511deea344225e

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/152

**Comment by kfarr** [comment]
Done!
https://github.3dstreet.org/#https://streetmix.net/burritojustice/16/

![image](https://user-images.githubusercontent.com/470477/163910192-7f37a9f5-eb94-40f8-8984-d6c891f1d756.png)
