### ISSUE TITLE
parked cars in parking spaces

### ISSUE THREAD

**Issue by srothst1** [3DStreet/3dstreet#147]
As a follow up to #144, we discussed either:
- Automatically placing one parked car in the middle of the parking lane street segment
- Randomly placing a random number of cars in the parking lane street segment

Any preference on which option we should move forwards with?

cc: https://github.com/3DStreet/3dstreet/pull/144#issuecomment-1091024737

**Comment by kfarr** [comment]
Simplest to start with just 1, the editor has a hotkey "d" to easily duplicate more cars if needed for a shot

**Comment by srothst1** [comment]
vehicles-in-parking-spaces

**Comment by burritojustice** [comment]
I just figured out how to clone and add objects, but I hope we can soon move to random placement. Not easy for new users to figure out how to do this, and I am not certain how/if you can easily share that scene outside a screenshot with a casual user.

Probably worth an issue to discuss how to populate lanes in general, and not just parking, when we go from a 2D Streetview slice to a 3Dstreet overview.

- bike lanes: is there just one type of cyclist? can also add scooters)
- travel lanes: should we do a mix of vehicle types? cars, SUVs, and trucks? can we randomize colors?
- parking: same as travel
- flex lanes: do we have a way to show rideshare? maybe a WiFi symbol hovering over a sedan? `)))`
- outdoor dining: just tables, or should we add parklets as well?

Do we randomly place people along the sidewalks, and buildings along a street?

**Comment by kfarr** [comment]
closed by #148

**Comment by kfarr** [comment]
also #245
