### ISSUE TITLE
Walking Animations 2.0

### ISSUE THREAD

**Issue by srothst1** [3DStreet/3dstreet#150]
Result: 8 separate `glb` files each with one of our low poly characters exhibiting a walking animation.

https://github.com/3DStreet/3dstreet-assets/tree/main/sets/human-characters-animation/gltf-exports

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/human-characters-animation-seperated/gltf-exports
I separated the characters and exported with walk animations.

**Comment by kfarr** [comment]
these were integrated as part of https://github.com/3DStreet/3dstreet/pull/181
closing
