### ISSUE TITLE
Animated Cyclists 2.0 

### ISSUE THREAD

**Issue by srothst1** [3DStreet/3dstreet#151]
Animations of five different low poly characters riding a bicycle. Please submit five `glb` files.

Please use the following three adult characters:

![image](https://user-images.githubusercontent.com/39531367/163631393-6084cff1-fd84-454b-9acd-91681f4d791a.png)

![image](https://user-images.githubusercontent.com/39531367/163631404-fd578b9d-4df6-4be0-a64c-182ff42e597d.png)

And the following two child characters:

![image](https://user-images.githubusercontent.com/39531367/163631487-23320546-5abd-4b6b-bef8-c39cedf8739a.png)

Please make sure that both children have helmets on.

**Comment by kfarr** [comment]
Draft provided on Discord channel. KF and JL provided feedback. Once the final animation is approved then we can go ahead and add the other character and bicycle type variants.
