### ISSUE TITLE
european style buildings

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#162]
from @kevincannon 
> here's some input on making the buildings more european style
> the tall buildings are actually fine, but removing the air-conditioning units, and front emergency stairs and they would then be pretty suitable for northern european cities.
![image](https://user-images.githubusercontent.com/470477/167043549-b6329a48-4091-4774-981a-8f2a3a259a10.png)

>  Here are some examples of fairly generic modern-ish buildings.
![image](https://user-images.githubusercontent.com/470477/167043682-f5b0c3d6-95af-4011-a041-f33131f542bb.png)

>  I think semi-detached houses and terraced housing are really common in the UK.
![image](https://user-images.githubusercontent.com/470477/167043694-7e96dbad-e942-4e1e-9adc-0dc9b1fbf1e4.png)
![image](https://user-images.githubusercontent.com/470477/167043703-80a7da34-4316-474d-bbc1-df2d5c690de9.png)

**Comment by burritojustice** [comment]
yeah, those buildings without fire escapes, and a surface material other than brick would be representative

**Comment by kfarr** [comment]
closing this ticket, follow here instead: https://github.com/3DStreet/3dstreet/issues/180
