### ISSUE TITLE
create 2 signal glbs:

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#168]
Goal is to provide 2 separate files:

1. a single traffic signal on a pole - signal1.glb
2. a traffic signal with 3 heads - signal2.glb

![signal-id](https://user-images.githubusercontent.com/470477/169118311-2d253224-77bc-4492-a528-e220864bd169.jpg)

**Comment by kfarr** [comment]
This folder is the source file for the signals
https://drive.google.com/drive/folders/1sgKrvQnoRxJlVRizvdtsERoUZacKaEhi?usp=sharing

Here is a blender file with 2 blends to help with this
- signal.blend - a single traffic signal head on a post
- mast.blend - a traffic signal pole with 3 signal head brackets

**Comment by kfarr** [comment]
Goal is to provide 2 separate files:
- #1 a single traffic signal on a pole - signal1.glb
- #2 a traffic signal with 3 heads - signal2.glb

![signal-id](https://user-images.githubusercontent.com/470477/169118311-2d253224-77bc-4492-a528-e220864bd169.jpg)

More notes:
- No textures should be used, instead convert to use the same global palette / atlas the other objects use.
- This should be added to the 3dstreet-assets repo to follow the same pipeline as other objects
- The placement of signal heads should match the same rotation as the reference scene composed of smaller model files here: https://github.3dstreet.org/examples/signals.html
- Remove the pedestrian signal (in mast.blend remove `bracket-ped` and `signal-ped` groups)

**Comment by gnansai** [comment]
@kfarr @srothst1 
I added signals here

https://github.com/gnansai/3dstreet-assets/tree/main/sets/signals/gltf-exports
https://github.com/gnansai/3dstreet-assets/tree/main/models/signals

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/169511290-796ed9de-24d4-48a7-b2af-137b4067de56.png)
![image](https://user-images.githubusercontent.com/25223402/169511358-53e4530a-0b2b-4a4a-9e3c-09cff0363a73.png)

**Comment by kfarr** [comment]
Thanks gnanasai, the only final input I have on these is to reduce the brightness of the yellow and red lights. They look too bright relative to the green and it makes it appear that they are "on" when the intention is that all the lights are off.

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/169641045-b07f3c54-aa15-48d8-98c6-81fe3231380c.png)

![image](https://user-images.githubusercontent.com/25223402/169641058-d8de96fb-1e2b-42cb-b19e-8d69911dbb8f.png)
I made the yellow light more darker

**Comment by kfarr** [comment]
@gnansai almost there... the red light should also be dark, the lights should all be "off" in these models. :) 

We will turn them "on" via the application at a later date.
