### ISSUE TITLE
Add stop sign model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#169]
Based on this
https://sketchfab.com/3d-models/stop-sign-ts-a3963ab8133b45cab4e60da94d255ac3

**Comment by kfarr** [comment]
can you extend the length of the post about 1.5x?

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/road-signs/gltf-exports
https://github.com/gnansai/3dstreet-assets/tree/main/models/road-signs
I added Stop Sign here
![image](https://user-images.githubusercontent.com/25223402/169515820-733ae106-0057-4d34-a27f-7207c707199f.png)

**Comment by kfarr** [comment]
Hi gnanasai, great progress! Here are a few more edits:
- can you increase the length of the pole by 1.5x?
- can you lighten the color of the pole to be more silver than dark gray?
- can you ensure that the 2 bolts continue past the back of the sign and through the back of the pole?
- the sign text itself uses incorrect typeface, below is a texture that you could use instead.
https://m.media-amazon.com/images/I/718IY5O2ZnL._AC_SL1500_.jpg

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/169640730-defb2527-a42a-4d5e-881d-a0c3772be6b6.png)
![image](https://user-images.githubusercontent.com/25223402/169640741-17d4b84b-72a2-4e7f-9bb1-d896ccaaf842.png)
I made these fixes

**Comment by kfarr** [comment]
excellent!

**Comment by srothst1** [comment]
Hi everyone. I am reopening this issue due to a small problem that I noticed while implementing stop signs in our new `intersection` component. As you can see in [this comment](https://github.com/3DStreet/3dstreet/pull/174#issue-1251136137), the stop sign is visible from both sides. Can we please resolve this?

cc @gnansai @kfarr
