### ISSUE TITLE
loud bicycle horn - mini

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#171]
Current:
![image](https://user-images.githubusercontent.com/470477/169201727-eb412040-c4ff-4a3f-a39c-b9dd1d15887b.png)
from: https://github.com/3DStreet/3dstreet-assets/blob/main/sets/cycle-horn/gltf-exports/cycle-horn.glb

Actual picture:
![image](https://user-images.githubusercontent.com/470477/169202182-a0dc3e30-2363-4724-8231-27d8f3764d19.png)
from: https://loudbicycle.com/horn

Question: does the mini horn need the mounting bracket on top? that appears to be missing

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/169527184-3e256ea3-4fc6-471a-91eb-32c9f7788d34.png)
I added mounting bracket. Do let me know if you need the holes in mounting bracket as the reference.

**Comment by JLansey** [comment]
This is great! thanks for adding the bracket on top. For now don't worry about the holes; we can come back to do that after everything else is done if there is time
It would be great to include this small version of our logo on the horn. Perhaps there is more space for it on the back. We're going to assume this won't be that big on the screen; so if we put the logo in the way it is on the actual horn then it might be too small.
![Speak Car](https://user-images.githubusercontent.com/4146681/169650227-2571bef6-24ec-44b3-ba7f-e8543cb54cda.svg)
.

**Comment by gnansai** [comment]
Hi @JLansey 
I added the Color logo on back as you have suggested
![image](https://user-images.githubusercontent.com/25223402/170045690-b49c6f56-22b7-420f-afd4-74e097c95ee0.png)

**Comment by JLansey** [comment]
I wish there were a prettier way to brand this - but for now this is excellent and we'll wait to see how it looks in the game.
