### ISSUE TITLE
Loud bicycle classic horn

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#172]
![image](https://user-images.githubusercontent.com/470477/169202815-f89a9051-ef59-4e05-aec1-17c04bca416a.png)
source: https://loudbicycle.com/horn#classic

**Comment by gnansai** [comment]
![unknown](https://user-images.githubusercontent.com/25223402/169524809-b4859098-3c81-46e7-9c88-4ef4e0b065e3.png)
![unknown](https://user-images.githubusercontent.com/25223402/169524820-692686bc-2584-4c01-8188-9b92a8889e84.png)
Here is an update on the classic horn

**Comment by JLansey** [comment]
Hi this looks great! Sorry we didn't have an image of the back of the Classic horn; it has more stuff on the backside to distinguish it from the mini.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/4146681/169649415-1f129e25-3336-4122-9436-6da0025b1a09.png">

**Comment by JLansey** [comment]
![loud icon](https://user-images.githubusercontent.com/4146681/169649495-1d4d98fa-f298-4ea7-914a-80fe070e5ab5.png)
Attached is the logo as an SVG
![loud_bicycle_logo_center](https://user-images.githubusercontent.com/4146681/169650171-a0019b9b-1ae3-404e-b425-799ed51b9b4a.svg)

I think it would be good to include this in orange on the side of the speakers OR on the back kind of where it is now. You don't need match the shape exactly in the back if it better facilitates placing the logo.

**Comment by JLansey** [comment]
Looks good for now! Great job matching the shape.
