### ISSUE TITLE
fire trucks

### ISSUE THREAD

**Issue by burritojustice** [3DStreet/3dstreet#173]
Could we add a fire truck? Nice to be able to show how much of a lane they take up. 

Think we’d need both pumper and ladder trucks:

https://hum3d.com/fire-truck/

https://3dmdb.com/en/3d-model/seagrave-ladder-fire-truck/317252/

and a smaller European-Japanese style fire truck

https://www.turbosquid.com/3d-models/3d-japanese-truck/705798

**Comment by kfarr** [comment]
http://ufsw.org/pdfs/apparatus_inventory.pdf

**Comment by kfarr** [comment]
scan of engine 29 https://poly.cam/capture/C1ACA0ED-C372-4786-A83A-FAD5689890A9 (not great quality but good enough for getting accurate dimensions of overall vehicle and key components)

**Comment by gnansai** [comment]
Hi @kfarr  @burritojustice 
I found few models that we can use.
1. Ladder truck - Low Poly model, It matches to our existing assest style. The materials needs to be converted to altas texture.
https://skfb.ly/6SzQI

2. Pumper Truck - I need to optimize this model so that it matches to our existing assest style.
https://skfb.ly/6XDDK

**Comment by gnansai** [comment]
Hi @kfarr 
Could you provide 3d model this photo scan model?
 https://poly.cam/capture/C1ACA0ED-C372-4786-A83A-FAD5689890A9

**Comment by kfarr** [comment]
Hi @gnansai here is a zip of the gltf:
[poly.glb.zip](https://github.com/3DStreet/3dstreet/files/10889039/poly.glb.zip)

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update on the fire ladder truck
![image](https://user-images.githubusercontent.com/25223402/225525736-20f5651a-64cc-4023-83be-1cd9bb3b68ce.png)
![image](https://user-images.githubusercontent.com/25223402/225525751-5ac9a9ee-c26d-4973-8842-fe78e66a33d6.png)
![image](https://user-images.githubusercontent.com/25223402/225525764-b7478637-4eba-488d-9a58-85e415831260.png)
![image](https://user-images.githubusercontent.com/25223402/225525783-07a13b15-5772-4647-bd43-a1f82ca0fb60.png)
![image](https://user-images.githubusercontent.com/25223402/225525898-826a83a8-32a8-4471-a738-1019f9541eb0.png)

**Comment by gnansai** [comment]
Hi @kfarr 
I have uploaded the files here
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles-rig/gltf-exports/draco/fire-truck-pumper-rig.glb
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/fire-truck-pumper.glb
https://github.com/gnansai/3dstreet-assets-source/blob/main/models/vehicles/fire_truck_pumper_v01.blend

**Comment by kfarr** [comment]
the assets above have been merged per https://github.com/3DStreet/3dstreet-assets-dist/pull/10/commits/8edf227e64bde541ddf4390d009972801cbbdb29 but not exposed in the app

should this only be accessible via the mixin chooser or another mechanism?

**Comment by kfarr** [comment]
next step try add to assets.js as a mixin using `src: url(...)` syntax instead of glb downloaded in assets

**Comment by kfarr** [comment]
facing this issue: 
https://github.com/aframevr/aframe/issues/5273
