### ISSUE TITLE
Animated bicycle model 2 - kid bike

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#175]
Need a kid bike and 1 kid animated biking on it

**Comment by kfarr** [comment]
Looks like there is a start here:

https://discord.com/channels/856013327917907991/907785761552740362/973940045541163128

https://user-images.githubusercontent.com/470477/170774359-ff5a0b55-c2c1-4b7a-9376-1d7737802a86.mp4

**Comment by gnansai** [comment]
Hi @kfarr 
Could you let me know if you have any specific suggestions on this model and animation?

**Comment by kfarr** [comment]
@gnansai can you do one final revision of this with a skinnier kid on the bike?

**Comment by gnansai** [comment]
@kfarr Sure

**Comment by kfarr** [comment]
@gnansai checking to see if the kid got any skinnier?

**Comment by gnansai** [comment]
https://skfb.ly/6SNSV
I could follow the Kid body proportions of this model.

**Comment by JLansey** [comment]
This kid model looks great :)

**Comment by gnansai** [comment]
Hi @JLansey  @kfarr 
I made changes to the Kid Body Proportions.
Please check when ever you are free and let me know if you need any fixes.
![image](https://user-images.githubusercontent.com/25223402/181428969-f210dd87-ac7c-49c3-a0e6-116a536edbdd.png)
![image](https://user-images.githubusercontent.com/25223402/181429014-001df4a8-370c-4e7d-91a7-89e09bc435b9.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/181429769-c9745f80-887b-46bb-be4b-c242530be836.png)
![image](https://user-images.githubusercontent.com/25223402/181429791-0547d8a2-5774-4125-a079-57384f126e8b.png)
I added Helmet

**Comment by JLansey** [comment]
Nice! Can we get rid of the weird large pockets?

**Comment by gnansai** [comment]
> Nice! Can we get rid of the weird large pockets?

yes

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/181875425-1c5131be-89ea-48fe-a2b2-67addb044575.png)
Hi @JLansey 
I removed the pockets

**Comment by gnansai** [comment]
Uploading kid_bicycle_animation.mp4…

Hi @JLansey @kfarr 
Here is the latest version of the kid bicycle animation.

**Comment by JLansey** [comment]
Looks a little bit fat - but overall quite good now! Thank you!

**Comment by gnansai** [comment]
> Looks a little bit fat - but overall quite good now! Thank you!

Shall I make him more skinny?

**Comment by kfarr** [comment]
I think this is good to mark as done, I merged into 3dstreet-assets
