### ISSUE TITLE
Animated bicycle model 3 - cargo bike

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#176]
Need animated cargo bicycle model with 1 human adult rider

**Comment by kfarr** [comment]
This was shared in the discord already
![image](https://user-images.githubusercontent.com/470477/170775020-e957cc77-e793-497c-a97c-ca1ea4818967.png)

**Comment by kfarr** [comment]
Revise to have only 1 box

**Comment by JLansey** [comment]
copying from discord to here:
in my opinion - it would be better with only one of those boxes; the two together look a little dangerous to bike with!
<img width="157" alt="image" src="https://user-images.githubusercontent.com/4146681/175665640-b513b36e-2b24-4abd-88f6-e5810d04d4fa.png">

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/cargo-bike-animation/gltf-exports
I added the cargo-bike-animation-here
![image](https://user-images.githubusercontent.com/25223402/175817389-a3e47e3d-8468-4bc7-8f54-67793060476c.png)

**Comment by kfarr** [comment]
Confirmed this is complete for 3d modeling and is now awaiting dev integration
