### ISSUE TITLE
Animated bicycle model 4 - dutch bike

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#177]
Key elements:
- curved top tube
- Swept back handlebar grips
- Upright position of rider (though could make all the rider touch-points equal to the other bike in order to simplify things.)

Best example to work from:
https://sketchfab.com/3d-models/tears-of-steel-bicycle-ba14f877e0314bbda00ef9eb28930422

1 animated human rider

**Comment by gnansai** [comment]
Hi @kfarr 
I tried to make it look like Dutch Bike.
Please check it and let me know if you have any suggestions. 

![image](https://user-images.githubusercontent.com/25223402/172177215-1cca6da5-b285-47fb-a3cd-ba45697baaa0.png)
![image](https://user-images.githubusercontent.com/25223402/172177283-57cd7fbc-bd1e-4cab-ac8a-ad7c98a8483d.png)
![image](https://user-images.githubusercontent.com/25223402/172177332-7483d405-a6b1-4936-9327-ce4ddfe731cf.png)

**Comment by JLansey** [comment]
Wow this bike looks great! Would love to see a person on it (they might need to be positioned more upright compared to the other bike)

**Comment by gnansai** [comment]
Hi @JLansey 
Please check this animation and Let me know if you need any fixes.
https://user-images.githubusercontent.com/25223402/172348630-eddc1d21-7281-48e4-8e94-3f0a788a77c9.mp4

**Comment by JLansey** [comment]
Nice job! Looks great! Could reduce the amplitude a little, but no bid deal either way.
