### ISSUE TITLE
Bar building

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#178]
Create a building that represents an Irish pubs with these Key elements:
- Facade includes, 1 door, and several repeating windows
- Single color scheme of blue/black/green/red - and words in gold.

Primary inspiration:
![image](https://user-images.githubusercontent.com/470477/170776064-7eb7b7cf-8de9-454a-a94c-396a7fbda66b.png)

https://free3d.com/3d-model/irish-pub-building-4628.html

**Comment by kfarr** [comment]
Primary inspiration:
https://free3d.com/3d-model/irish-pub-building-4628.html

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update on Irish Pub.
I have to add 
*Door
*Golden color Text
*Flag
*Board
![image](https://user-images.githubusercontent.com/25223402/172087871-67cf306e-adc9-4a2b-a1af-e2e09cccc49f.png)
Please check it  and let me know know if you need any changes or fixes.

**Comment by kfarr** [comment]
Looks like a good start! I'd suggest to continue and we'll solicit feedback from the group once you've completed the other elements

**Comment by JLansey** [comment]
1) I think the color green is better - this kind of looks like a police-box / the tardis in blue.
2) Remove the flag
3) Lets see how the windows look once the color is changed, but right now they look too lifeless, as if the bar is closed; maybe show then with an orange glow behind them like the this picture below. Lets also turn on the lights above the bar
<img width="370" alt="image" src="https://user-images.githubusercontent.com/4146681/172328282-1eae9b73-7016-4c94-a072-8a58d84d2c19.png">

**Comment by gnansai** [comment]
Hi @JLansey 
Thanks for the Suggestions. I have made changes as per your suggestions. Please check this and Let me know if you need any fixes. 
![image](https://user-images.githubusercontent.com/25223402/172353172-1908efda-a82a-46c9-a2ec-713e4d061568.png)

**Comment by JLansey** [comment]
Looks nice - I think we can remove "Bar & lounge" text. 
EST. 2012 would be cool (that is when Loud Bicycle was founded).
Also - I think I mentioned before - but putting a tad of variation in the brightness in the windows should make it look a lot more realistic I think.

The color green could be improved if we make it one of the color below; right now I think it looks too desaturated (but maybe that is just because it is at night?)

<img width="699" alt="image" src="https://user-images.githubusercontent.com/4146681/175665034-9cd66439-04ed-425e-9ef9-5482874cd75b.png">

Overall this looks great! I'm excited about it being called the "Loud Bar"

**Comment by gnansai** [comment]
I updated the Irish-bar-building
![image](https://user-images.githubusercontent.com/25223402/175819374-89b86bbd-e1c6-4acc-89a9-097558baff31.png)

https://github.com/gnansai/3dstreet-assets/tree/main/sets/irish-bar-building/gltf-exports

**Comment by kfarr** [comment]
Approved good for now, we may need to adjust lighting of the windows (emissive, etc.) when we place this in an actual night scene

**Comment by JLansey** [comment]
I think this one looks a bit better -what do you think?
#232323

<img width="347" alt="image" src="https://github.com/3DStreet/3dstreet/assets/4146681/c9932f3d-764d-4d39-97f3-b36aeef82e7b">

**Comment by kfarr** [comment]
@JLansey confused what you are referring to... are you saying that the colors of the dark windows should be changed to the RGB hex value of #232323 ? And there are no other color changes requested?

**Comment by kfarr** [comment]
@gnansai final change request is to make the windows a bit brighter #232323 instead of dark black, this should be the final change needed
