### ISSUE TITLE
School building - basic

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#179]
Basic low poly school with key elements inspired by this object:
https://free3d.com/3d-model/low-poly-school-building-4349.html

We can also purchase this and modify if easier

**Comment by gnansai** [comment]
Hi @kfarr ,
Here is an update on school building model.
![image](https://user-images.githubusercontent.com/25223402/172042365-9007cb04-0e81-4425-b972-b5955fbbcbe4.png)
![image](https://user-images.githubusercontent.com/25223402/172042374-4bfded83-64b8-44da-80cd-4ce2d1f0430e.png)

**Comment by JLansey** [comment]
I think this looks great!

**Comment by kfarr** [comment]
This is done, now moving to awaiting implementation status
