### ISSUE TITLE
Modify existing dense buildings to make them less east-coast

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#180]
- remove fire escapes
- remove air conditioners and ventilation ducts from roof
- removing air conditioners from window units

**Comment by gnansai** [comment]
Hi @kfarr Could you point me to the "existing dense buildings" on github?

**Comment by kfarr** [comment]
@gnansai here is the output set:
https://github.com/3DStreet/3dstreet-assets/blob/main/sets/buildings/gltf-exports/buildings.glb

I think the source is here:
https://github.com/3DStreet/3dstreet-assets/blob/main/models/buildings/buildings.blend

**Comment by kfarr** [comment]
Also remove the stylized dark red brick elements on the front face

**Comment by gnansai** [comment]
Hi @kfarr 
I removed the 
*fire escapes
*air conditioners and ventilation ducts from roof
*air conditioners from window units
![image](https://user-images.githubusercontent.com/25223402/172035744-9ab6fa07-1732-4064-ace0-64a0a9454326.png)
![image](https://user-images.githubusercontent.com/25223402/172035753-8f2c2beb-128d-4aa1-99a9-73bd9e58468f.png)
![image](https://user-images.githubusercontent.com/25223402/172035759-a1c52e8c-83f9-48ef-972c-b43c61fb5395.png)
![image](https://user-images.githubusercontent.com/25223402/172035774-784ceec2-bf64-4119-a445-f7f009921465.png)
![image](https://user-images.githubusercontent.com/25223402/172035786-103d1c9d-03c5-496c-ac1d-efbbe2e800bd.png)

**Comment by gnansai** [comment]
I updated the buildings glb here
https://github.com/gnansai/3dstreet-assets/tree/main/sets/buildings/gltf-exports

**Comment by kfarr** [comment]
This is great progress! Can you also remove:
- billboard frame
- satellite dish
- green slanted roof box on the roof

**Comment by gnansai** [comment]
Sure, I removed 
*billboard frame
*satellite dish
*green slanted roof box on the roof
![image](https://user-images.githubusercontent.com/25223402/172037449-10443943-7327-4d25-b069-ef9624b45bd7.png)
![image](https://user-images.githubusercontent.com/25223402/172037456-b75a0d40-4027-424a-bbe4-7476833d4c14.png)

**Comment by kfarr** [comment]
Thanks Gnanasai! I'd say this task is complete from a 3d model perspective and now awaits implementation

**Comment by kfarr** [comment]
Great, looks done to me!

**Comment by kfarr** [comment]
The buildings are here in `3dstreet-assets-source`
https://github.com/3DStreet/3dstreet-assets-source/blob/main/sets/buildings/gltf-exports/buildings.glb

They should also be updated to meshopt -cc per https://github.com/3DStreet/3dstreet/issues/198

Also they should no longer use `model-center` component in assets.js after this change, it is no longer necessary since gnanasai has correctly centered the models: (in fact no model should use this, including suburban buildings, it is not necessary to use this component)
https://github.com/3DStreet/3dstreet/blob/main/src/assets.js#L111

**Comment by kfarr** [comment]
closed by #233
