### ISSUE TITLE
add `wheel` component to rotate wheels of compatible assets

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#190]
Suggested steps:
- [x] create a new branch that migrates the `wheel` component from https://glitch.com/edit/#!/wealthy-rural-larch to a new component in this file: https://github.com/3DStreet/3dstreet/blob/main/src/index.js
- [x] migrate the demo from glitch to `wheel.html` or similar
- [x] document how to prepare a model that is compatible with this component (just a few sentences)
- [x] document how to use the component in a similar fashion to https://github.com/3DStreet/3dstreet/blob/main/README.md#a-frame-street-component-api
- [x] update vehicle animation logic to include the wheel component https://github.com/3DStreet/3dstreet/blob/main/animated.html (this might replace the need for `wheel.html`)

I can help with some of the later steps once you get the first few steps implemented on a branch

**Comment by gnansai** [comment]
Hi @kfarr 
I don't have write access to 3Dstreet. I might not be able to create new branch.
Shall I create a fork instead of branch?

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/tree/vehicle-wheel-animation

**Comment by gnansai** [comment]
Hi @kfarr 
I added documentation here
https://github.com/3DStreet/3dstreet/blob/vehicle-wheel-animation/README_vehicle-wheel-animation.md

**Comment by gnansai** [comment]
I tried adding animation to wheels.
https://github.com/3DStreet/3dstreet/blob/vehicle-wheel-animation/animated.html
I added links to new vehicle assets-rig here 
https://github.com/3DStreet/3dstreet/blob/vehicle-wheel-animation/src/assets.js
I modified here to add wheel rotation.
https://github.com/3DStreet/3dstreet/blob/vehicle-wheel-animation/src/aframe-streetmix-parsers.js

https://user-images.githubusercontent.com/25223402/185725800-a659b254-3578-46c7-aa21-a4b34ef45123.mp4
I have to implement the relation between speed of the vehicle and wheel rotation.

**Comment by gnansai** [comment]
https://user-images.githubusercontent.com/25223402/185725843-f0005bb1-e5d2-43a6-a91e-aef97c48b8ce.mp4

**Comment by gnansai** [comment]
I have to implement the relation between speed of the vehicle and wheel rotation in this new Animation system.

**Comment by kfarr** [comment]
Thanks for the help on discord to merge this. There are still a few things to cleanup that I am continuing on the same branch:
https://github.com/3DStreet/3dstreet/tree/vehicle-wheel-animation

- would like to only have 1 set of assets (rigged vehicles instead of non rigged)
- need to update assets-dist repo as well as assets.js and aframe-streetmix-parsers.js to reflect one set of vehicle assets

**Comment by kfarr** [comment]
Ok merged the rest of the fixes here: 
https://github.com/3DStreet/3dstreet/pull/195

Created separate ticket to track consolidating assets:
https://github.com/3DStreet/3dstreet/issues/199
