### ISSUE TITLE
Option to enable animations by default

### ISSUE THREAD

**Issue by srothst1** [3DStreet/3dstreet#196]
For loud bicycle game we need ability to enable all animations by default

Here is one implementation option:
flag on street component like enableAnimations similar to [showGround](https://github.com/3DStreet/3dstreet/blob/main/src/index.js#L15) or showStriping with default = true. When set to true all object that include an animation are animated

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/201
