### ISSUE TITLE
add draco compression to all assets

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#198]
steps:

- [x] create demo that works with new compression and 1 asset
- [ ] update 3dstreet repo to support new compression
- [ ] update the 3dstreet-assets-dist repo to compress the assets

**Comment by kfarr** [comment]
Ok please note that I changed the structure of the repos
There are now 2 repos for assets
* https://github.com/3DStreet/3dstreet-assets-dist
* https://github.com/3DStreet/3dstreet-assets-source

`3dstreet-assets-source` is the same repo as the old `3dstreet-assets` simply renamed
Whereas 3dstreet-assets-dist ONLY has compressed files for distribution
Also 3dstreet-assets-dist is CNAMED to assets.3dstreet.app

I attempt to maintain the same directory structure on both but simply to not include any source files or unneeded files in `3dstreet-assets-dist`

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets-dist/tree/main/Gltf-BatchConvertor
I wrote Node js script for Batch processing glb files.
It adds meshopt compression  `gltfpack -i ${file} -o ${file} -cc -kn`  on all glb files.

**Comment by djoksimo** [comment]
Although I understand this issue is regarding batch gltf processing since there's lots of models, I thought I'd share [this tool](https://gltf.report) that I found to be super handy for inspecting, processing, and compressing gLTFs: https://gltf.report

**Comment by gnansai** [comment]
Thanks for sharing this tool.

**Comment by kfarr** [comment]
Hi @gnansai sorry for the delay. Thank you for providing the script.

The goal of this is to have the meshopt compressed files in a separate path, not to replace the uncompressed versions. We should follow the same /meshopt/ directory structure that we used in loud bicycle game assets, such as this example:
https://github.com/3DStreet/3dstreet-assets-dist/tree/main/sets/cargo-bike-animation/gltf-exports/meshopt

Can you update your fork to reflect that? https://github.com/gnansai/3dstreet-assets-dist

**Comment by kfarr** [comment]
Also the newly meshopt compressed files in this assets `dist` repo should match the same /sets/ directory structure found in `source` repo.

No new objects should be placed in the /objects/ directory

**Comment by kfarr** [comment]
After testing and discussion from @Algorush we have decided to use draco instead of meshopt. Meshopt has 2 issues that would need more work to resolve:
* the meshopt library has unknown side effects when loading that sometimes result in console errors (https://github.com/aframevr/aframe/pull/5156#issuecomment-1322635913) apparently related to gltf animation functionality
* we were not able to get meshopt compressed files to respect names for objects that could be filtered without code changes, currently used for buildings, dividers and other street props (possible related to https://github.com/zeux/meshoptimizer/issues/201)

**Comment by kfarr** [comment]
this ticket got too complicated, closing and re-wrote a simpler version: https://github.com/3DStreet/3dstreet/issues/239
