### ISSUE TITLE
wheels do not spin at expected speed

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#203]
- instead of using test method with bone z position changing each frame, should use the same method in production with animated cars
- in doing so there is an approx 3x offset -- the car wheels are spinning 3x slower
- see /animated.html (https://github.3dstreet.org/animated.html)

suggested resolution:
you can add `* 3` to link and it looks better
`     const distx = speed * 0.003 * 3;`
[on this line](https://github.com/3DStreet/3dstreet/blob/main/src/index.js#L387)

**Comment by gnansai** [comment]
Hi @kfarr 
I made the change that you suggested.
https://github.com/3DStreet/3dstreet/compare/main...wheel-animation

**Comment by gnansai** [comment]
We have to add relation between the vehicle movement and vehicle wheel rotation.
Could you point me to the part of the code which is making the vehicle to move forward?

**Comment by kfarr** [comment]
@gnansai Here is where the speed and animation are set for vehicles:
https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L307

**Comment by gnansai** [comment]
Hi @kfarr 
I reworked on the WheelRotation. I simplified the formula. 
https://github.com/3DStreet/3dstreet/blob/wheel-animation/src/index.js#L386

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/210
