### ISSUE TITLE
building position exceeds length of street

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#204]
issue: when using length on a street with suburban or urban buildings enabled the buildings can exceed the length of the street
impact: buildings are incorrectly placed on top of perpendicular streets and sidewalks.
instead: buildings are not placed in a position where any of the building mesh overlaps beyond the street length

See A in this screenshot for suburban example: (ignore B, that is another issue)
![image](https://user-images.githubusercontent.com/470477/189801493-30e85fba-71de-4a2a-996d-8574d1f160d3.png)

And urban example:
![image](https://user-images.githubusercontent.com/470477/189801673-802eedf6-79ed-48a5-a236-c64fe8c0683d.png)

From this branch on loud bike project:
https://github.com/3DStreet/loud-bicycle-game/tree/side-streets

**Comment by Algorush** [comment]
> From this branch on loud bike project:
> https://github.com/3DStreet/loud-bicycle-game/tree/side-streets

Hi Kieran. This page doesn't work. So can you or anyone else help please, where I can find examples with this issue

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/208
