### ISSUE TITLE
v1 save element and children to javascript object

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#207]
Goal - create a function that takes one or more elements (from a DOM queryselector call) and returns a Javascript object as follows:

Desired output format:
```
[
  { element: 'a-entity', components: [{position: "0 0 0"}, {rotation: "0 0 0"}], children: [{...}, {...}] },
  { element: 'a-entity', components: [{position: "0 0 0"}, {rotation: "0 0 0"}], children: [{...}, {...}] },
  (...)
]
```

**Comment by kfarr** [comment]
Some more points:
* this should be a standalone file for now such as /src/json-utils.js
* the first test for this function will be to copy and paste it into the console and run it
* it will be run on this URL: https://json-test-case.glitch.me/
* the element passed will be created by `const elementToConvert = document.querySelector('#container')`
* then to call a function such as `result = convertToObject(elementToConvert)`

**Comment by vincentfretin** [comment]
You should look at the `getEntityClipboardRepresentation` function in `lib/entity.js` that is used with the "Copy entity HTML to clipboard" button in the default aframe-inspector. We want the same but in json, and for several entities. There is probably some functions you can reuse or refactor so that you can use them for both html and json serialization.
I'd probably put id and class out of components here.
@kfarr we discussed a slightly different format, components should be an object, not an array, so that is similar to the `createEntity` api in `lib/entity.js`
So it should be something like this:
```
const data = {data: [{
  element: "a-entity",
  id: "container",
  class: "box-sphere",
  children: [
    {element: "a-box", components: {position: "-1 0.5 -3", rotation: "0 45 0", color: "#4CC3D9"}},
    {element: "a-sphere", components: {position: "0 1.25 -5", radius: "1.25", color: "#EF2D5E"}
  ]},
  //    (... etc to include cylinder, plane, sky)
]}
```

`element: "a-entity"` can be omitted.

To serialize that to a string, just use `JSON.stringify(data)`.

For the import, you can modify the `createEntity` function to fallback on "a-entity" if element is not defined, add support to set id and class attributes, and add support for children in a recursive way.
Example of creating an entity with a glb:
```
Events.emit('entitycreate', {
  element: 'a-entity',
  components: {
    'gltf-model': '/model/url.glb',
    position: "2 0 3"
  }
});
```

**Comment by vincentfretin** [comment]
Probably for later if you want to save to a server only entities that changed, or do some collaborative editing (I'm planning to work on that myself), be aware that in `lib/history.js` you already have a normalized structure of the entities that changed during the session via the various `entityupdate` events emitted during the session, actually only the components that changed, so not all components for a given entity. It may be interesting later to have a full normalized store of the entities, with a last_modified field for each entity, but we'll figure this out later.

**Comment by kfarr** [comment]
From @Algorush 
>  ran into a little problem so far. For some reason I lose the contents of the components property of the child elements. So far, I do not understand at what stage. I will continue tomorrow

**Comment by Algorush** [comment]
made a PR with the first version(https://github.com/3DStreet/3dstreet/pull/211) 
Component information can be retrieved from the components property of Entity, where it is stored as an object, such as position: {'x':'1', 'y':'2', 'z':'3'}. But today I noticed that the components property is not always present in an Entity. Maybe someone knows why? 
Therefore, I used the attributes Entity property, in which the information is stored as a string: position: 'x:1 y:2 z:3'

**Comment by kfarr** [comment]
This is an excellent first iteration, thank you @Algorush !

Against the test case I proposed of https://json-test-case.glitch.me/ this works as expected! Thanks for incorporating Vincent's suggestions to include some compatibility with the existing `createEntity` function from the editor.

Here is a new test case:
* Open https://github.3dstreet.org/#https://streetmix.net/kfarr/83/south-van-ness-idea-short-term
* Paste the new [`src/json-utils.js`](https://github.com/Algorush/3dstreet/blob/save-element-to-object/src/json-utils.js). Here's a minified copy/pasta for convenience:
```
function convertToObject(e){let t=[];if(e.length)for(let n of e)t.push(getElementData(n));else t.push(getElementData(e));return{data:t}}function getElementData(e){let t=getAttributes(e);var n=e.childNodes;if(n.length)for(let a of(t.children=[],n))a.nodeType===Node.ELEMENT_NODE&&t.children.push(getElementData(a));return t}function getAttributes(e){let t={},n=Array.from(e.attributes).filter(e=>!("id"==e.name||"class"==e.name));if(e.id&&(t.id=e.id),e.className&&(t.class=e.className),t.element=e.tagName.toLowerCase(),n)for(let a in t.components={},n){let l=n[a];t.components[l.name]=l.nodeValue}return t}
```
* Paste the following in the console:
```
const elementToConvert = document.querySelector('#street-parent')
result = convertToObject(elementToConvert)
JSON.stringify(result)
```
* The output I expect is to include position, rotation and other components or attributes that were generated during the runtime of the application (these components or attributes were not defined in the original html). Right now the components appears as keys but the values are empty strings.

@vincentfretin would love your review and advice here too!

**Comment by kfarr** [comment]
I just saw your update to the PR #211 , here is the result of test case 2:
* a spot check of entities in the output show that they now contain both the attribute/component name as well as the value
* after modifying a position in the inspector and then re-running the above, the position component is reflected correctly on the output

I think this is good enough to merge for a "v1" of a pretty generic save to js object function and then we will open a new ticket for next steps

**Comment by vincentfretin** [comment]
For me the implementation is wrong, this is saving all the default values of the components, see all the default values for geometry or material components, we don't need to save all that. It should just save the values you set. See the `prepareForSerialization` function that uses the `getOptimalUpdate` function in `lib/entity.js`.

**Comment by kfarr** [comment]
@vincentfretin Thanks Vincent! Yes I agree it is not helpful to have the default component values.

To be clear here was the order I was trying to achieve before going to Editor code which is v3:
* v1 Save to JSON object from html defined scene (done, working as expected)
* v2 Save to JSON object from scene modified at runtime (partially complete, but includes all default component values. End state desired: do not include default component values.)
* v3 Save to JSON object from a scene that was edited with the inspector (not started)

For v2 -- do you have a recommendation of how we might not include the default values?

**Comment by Algorush** [comment]
I found function getModifiedProperties in entity.js. It is much simpler and uses a comparison with the default value from components[componentName].schema. Is this functionality suitable for our purposes? The only thing I noticed is that not all components have a schema, for example, position, rotation. Is it enough to set the condition that if the component does not have a schema, then leave this value for data?

**Comment by vincentfretin** [comment]
All components have a schema, even position and rotation, they use a single-property schema, so with no explicit field name.

**Comment by vincentfretin** [comment]
see https://github.com/aframevr/aframe/blob/6fba52f875b84c30420942f329fef3a5c8a4e821/src/components/position.js#L4

**Comment by Algorush** [comment]
I'm understood, thank you. That is, I can use `components[componentName].hasOwnProperty('schema')` to check such properties?

**Comment by vincentfretin** [comment]
Please take the time to read the current implementation to serialize in html, you have the code right there with the `isSingleProperty` check:
https://github.com/aframevr/aframe-inspector/blob/1dade31e67c0a19bc861af917b8ea1009d603089/src/lib/entity.js#L441-L443

**Comment by kfarr** [comment]
Ok very good progress here! For test case 1, the output of `convertToObject` is looking almost identical to Vincent's suggestions above. (Test case 1 didn't include classes but support was added to the function.)
[result-test-case-1.json.zip](https://github.com/3DStreet/3dstreet/files/9845757/result-test-case-1.json.zip)

**Comment by kfarr** [comment]
For test case 2 the output of `convertToObject` also looks similar to the expected output especially including elements added during runtime as requested. Copy attached.
[result-test-case-2.json.zip](https://github.com/3DStreet/3dstreet/files/9845765/result-test-case-2.json.zip)

I'm going to try to merge and mark this ticket closed again (we can open pending more feedback from @vincentfretin). I'll add notes after testing json loading on https://github.com/3DStreet/3dstreet/issues/212 and open new tickets or reopen this one if needed.
