### ISSUE TITLE
`gltf-helpers` should not be a dependency

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#238]
https://github.com/kfarr/aframe-gltf-helpers
the repo has been marked as "[not super great](https://github.com/kfarr/aframe-gltf-helpers#aframe-gltf-helpers)"
* move anisotropic filtering component to 3dstreet project
* stop using gltf-part-plus component, just use gltf-part

**Comment by Algorush** [comment]
Use gltf-part from third party module? There is no built-in gltf-part in AFrame as far as I know
https://www.npmjs.com/package/aframe-gltf-part-component

**Comment by kfarr** [comment]
Hi @Algorush correct instead of using this dependency we should split objects into separate glbs

However we should migrate `anisotropy` component into the 3dstreet repo

**Comment by kfarr** [comment]
Hey @Algorush because of the challenges of https://github.com/3DStreet/3dstreet-assets-source/issues/44 I would suggest to instead use this component and keep things in parts for now:
https://www.npmjs.com/package/aframe-gltf-part-component

If any objects are not positioned correctly then we should change them in the gltf, not via runtime code.

Again the goal is to stop using the specific library here: https://github.com/kfarr/aframe-gltf-helpers so that we have 1 less thing to maintain

**Comment by Algorush** [comment]
created PR for move anisotropy component: https://github.com/3DStreet/3dstreet/pull/249
created PR for gltf-part component: https://github.com/3DStreet/3dstreet/pull/252

**Comment by kfarr** [comment]
closed with #249 and #252
