### ISSUE TITLE
add draco compression for all assets

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#239]
For all 3dstreet models in the `3dstreet-assets-source` repo `sets` directory, they should have draco compressed versions available in the corresponding `3dstreet-assets-dist` repo

The `dist` repo should only contained compressed version of assets. Leave the meshopt versions in there, but we are going to add draco versions for all of the existing `3dstreet-assets-dist` sets AND for sets in `source` repo but not yet copied to `dist`

For draco compressed objects in `/3dstreet-assets-dist/sets/` The path structure should be:
`3dstreet-assets-dist/sets/[set-name]/gltf-exports/draco/`
similar to the existing structure for meshopt files

Only the `glb` file needs to be created in that directory, not gltf + bin

Here is an example.

The `dividers` set is currently in the source:
https://github.com/3DStreet/3dstreet-assets-source/tree/main/sets/dividers/gltf-exports/dividers.glb
this is an uncompressed glb file

The task is to create a glb draco compressed version that will still respect gltf part names and to place that file in
https://github.com/3DStreet/3dstreet-assets-dist/tree/main/sets/dividers/gltf-exports/draco/dividers.glb

Once all these assets are created, then the task is to add them into the 3dstreet assets.js file with the new paths to the draco compressed versions.

**Comment by Algorush** [comment]
Created 2 PRs:
1. for new Glb files in 3dstreet-assets-dist: https://github.com/3DStreet/3dstreet-assets-dist/pull/3
2. for assets.js file: https://github.com/3DStreet/3dstreet/pull/241

**Comment by kfarr** [comment]
done! https://github.com/3DStreet/3dstreet/pull/241
