### ISSUE TITLE
compress fence, bus model with draco

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#242]
add to 3dstreet-assets-dist repo and also update 3dstreet repo /src/assets.js file

fence: no file uploaded as part of draco PR, removed from assets.js to make the initial merge work https://github.com/3DStreet/3dstreet/pull/241

bus model: @Algorush I think you mentioned you could might be able to further compress images in flyer-bus.glb?

**Comment by Algorush** [comment]
> add to 3dstreet-assets-dist repo and also update 3dstreet repo /src/assets.js file
> 
> fence: no file uploaded as part of draco PR, removed from assets.js to make the initial merge work #241
Forgot to upload fence glb.

> bus model: @Algorush I think you mentioned you could might be able to further compress images in flyer-bus.glb?
Yes, Dealt with installing ktx-software (https://github.com/KhronosGroup/KTX-Software) libs to compress textures in gltf/glb (on Windows via cmake and others)

**Comment by kfarr** [comment]
@Algorush - ok should be easy to upload a draco compressed fence?

For compression, the short-term goal is compression of images to reduce download size of the jpeg and png files that become embedded in a GLB file. Not using KTX gpu compression which has a primary goal of performance improvement and webgl memory optimization.

The suggested workflow for this is to reduce the texture file dimensions proportionately and/or re-compress the jpeg or png with specialty tools. For example I have seen success using free tools online to compress png files as they discard unused palette colors, alpha layer, etc. Similarly with jpeg we can significantly decrease quality upon compression to decrease file size (ie from 90% compression quality to 30% compression quality) which usually isn't noticed in 3d object textures in non-vr mode.

**Comment by Algorush** [comment]
Added fence4.glb in Draco version: https://github.com/3DStreet/3dstreet-assets-dist/pull/5

**Comment by Algorush** [comment]
I changed path to new fences glb file with Draco compression in assets.js: https://github.com/3DStreet/3dstreet/pull/243

**Comment by kfarr** [comment]
Looks great!
