### ISSUE TITLE
Add support for elevation from streetmix segment

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#244]
Streetmix segments API response can now include a new `elevation` property. ([example API response](https://streetmix.net/api/v1/streets/7a633310-e598-11e6-80db-ebe3de713876))
 
- the elevation property is usually 0 or 1, with 0 = road level, and 1 = sidewalk level. we don't use "actual" elevation values (unlike widths), because we're not really concerned about elevation precision from an engineering standpoint. elevation heights in streetmix have always been for illustrative purposes only. there are a few other possible values for unique cases (elevated transit platforms and drainage channels)
- streets data on the next schema version will be updated so "elevation" is a property of each segment. (we don't do bulk updates of street schemas -- they're only updated when someone accesses one client-side)
- changing segment variants will update that elevation property. while some segments have a specific "elevation" variant defined, it's also the case that some segments change the elevation within a non-elevation-specific variant. a good example of this is the "divider" element where we have things like sidewalk-height greenscape planters and road-level bollards.
- in the near future, it will be possible for a segment to have a control that modifies the elevation value directly, and there won't be a segment variant for that. the first one will be the sidewalk segment. this will be behind a feature flag and will roll out initially to beta testers.
**- for downstream consumers of the Streetmix API (like 3DStreet) it would be a good idea to pick up that elevation property when it's there, and be prepared for a data schema where the "elevation" variant is removed in favor of reading elevation from the segment property (but this will not happen yet)**

How 3DStreet does elevation now?
* 3dstreet "makes a guess" on elevation based on the segment and variant -- if it's a sidewalk it is higher elevation than other segment types.

What should change?
* If a streetmix segment has an explicit elevation, then respect that choice. Otherwise continue to "guess" using the current logic to make sidewalks higher elevation than other segments.

Related previous work:
* https://github.com/3DStreet/3dstreet/pull/186#issuecomment-1257008569

**Comment by Algorush** [comment]
Created First PR: https://github.com/3DStreet/3dstreet/pull/256
I have so far defined elevation=1 and if so, the same code is used as for the sidewalks now (geometry box and height = 0.4). In other cases (elevation = 0) the same code as before is used - in some cases it is box geometry with height = 0.2 (for all lanes), in others - plane geometry. 
@kfarr tell me if I understood correctly

**Comment by kfarr** [comment]
Looks good, tested with this scene: http://localhost:7001/#https://streetmix.net/igreensf/24/arguello-residential-future

Previously the segment to the right of the bike lane was not elevated, now it is correctly elevated with this change

![Image](https://user-images.githubusercontent.com/470477/230753971-9a2b78aa-d52a-4fba-b27f-d89a2ef66697.png)

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/pull/256
