### ISSUE TITLE
for vehicles placed in parking lanes, add more than 1 per scene

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#251]
in the parking lane, we want to be able to place more than 1 vehicle, ideally about 5. Perhaps this is a variable that can be configured in the future?

**Comment by kfarr** [comment]
for example to randomly place so it might have additional cars in the red boxes here:

![Image](https://user-images.githubusercontent.com/470477/225671834-7098ab78-23fb-4bba-966a-0d134aa273d6.png)

**Comment by Algorush** [comment]
created PR: https://github.com/3DStreet/3dstreet/pull/255

**Comment by kfarr** [comment]
closed by #255
