### ISSUE TITLE
support perpendicular parking segment from streetmix

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#264]
https://streetmix.net/tomasborja21/1/university-blvd has a perpendicular parking segment

this is not displayed correctly in 3dstreet

instead, vehicles should be placed perpidincularly in parking stalls automatically when selected

**Comment by Algorush** [comment]
In this example, there is also a building type that is not yet supported in 3DStreet: parking-lot

**Comment by kfarr** [comment]
closed with #273
