### ISSUE TITLE
arrows keyboard control not working after switching viewer->editor->viewer

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#267]
I noticed that after switching from the editor mode back to the viewer, the camera control with the arrows on the keyboard stops working. I will try to fix it

**Comment by kfarr** [comment]
yes would be happy to have you take a look! but this is a duplicate, so I will close this ticket and reassign you to this one:
https://github.com/3DStreet/3dstreet-editor/issues/130
