### ISSUE TITLE
use c-frame cursor teleport

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#270]
We can now leverage the C-Frame maintained cursor teleport component. The customized version here: https://github.com/kfarr/aframe-cursor-teleport should no longer be needed to support our features.

Also review this PR to test ipad cursor visibility change:
https://github.com/c-frame/aframe-cursor-teleport/pull/57

**Comment by vincentfretin** [comment]
https://github.com/c-frame/aframe-cursor-teleport/pull/57 has been merged and I build new dist on master.
Your fork still contain some changes you may want to have upstream, those are:
- https://github.com/c-frame/aframe-cursor-teleport/issues/58
- https://github.com/c-frame/aframe-cursor-teleport/issues/52
