### ISSUE TITLE
regression - parallel parking spot should still use "T" marking

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#286]
prior to adding perpendicular and angled parking (https://github.com/3DStreet/3dstreet/pull/273) the parallel parking spaces looked like this:
![original-parking-spots-screenshot-3dstreet-1681162742960 copy](https://github.com/3DStreet/3dstreet/assets/470477/c0112b4d-02f8-42e5-bcb7-5e5341880e23)

after 273 they look like this:
![image](https://github.com/3DStreet/3dstreet/assets/470477/a3d83963-cb4b-44eb-8b1d-c273b258934a)

for parallel parking they should be reverted to use the "T" symbols

the changes to perpendicular and angled parking are ok and should remain

**Comment by Algorush** [comment]
ok, I guess I misunderstood last time.

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/pull/302 thank you @algorush!
