### ISSUE TITLE
support loading a 3dstreet json file from URL hash

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#288]
in the same manner as a streetmix street can be loaded by providing its url in the hash, so should we be able to load a 3dstreet.json file. Here is an example URL structure for this:
`https://3dstreet.app/#https://hostname.com/file.3dstreet.json`
where in this example "https://hostname.com/file.3dstreet.json" will be loaded

for now this should be implemented next to the current equivalent code for streetmix load from hash, and then perhaps we should wrap loading support in general as a component such as `loader-3dstreet` on the `scene` entity

**Comment by Algorush** [comment]
Can you please give a direct link to the test JSON file with the scene? So far I have made an option that only works with files on the local server, I need to test with remote. Google disk, github does not provide a direct link to the files

**Comment by kfarr** [comment]
Hey @algorush yes we can add to the repo some json scene files samples and use those for testing. They will be accessible in PR state via netlify build URL and upon merge via github pages URL. I will do this in the next day or so, test the PR, and then merge if it's working.
