### ISSUE TITLE
save / load - support environment node

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#292]
save environment node in 3dstreet json and support loading of it

- the environment entity has "street-environment" component - it will save day or night as part of the component property. that is the only thing we need to save at the moment.
- do not save any children of environment component such as lights or sky, they should be generated dynamically based on the street-environment component

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/300

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/issues/303 is a blocker to be done prior to this ticket 292 being possible to complete

**Comment by kfarr** [comment]
closed by #300  and #303
