### ISSUE TITLE
save / load - support 2d layer node

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#295]
in many cases this node is not used

here is an example of it being used 
https://github.3dstreet.org/mapbox.html

in this example, the mapbox satellite street layer should be saved under 2d layer node

**Comment by Algorush** [comment]
In order for the scene loading with the mapbox component to work, I added component code (aframe-mapbox-component.min.js) to the src/lib folder and changed THREE.Math to THREE.MathUtils, since THREE.Math is not supported in new versions of three.js

**Comment by Algorush** [comment]
I also found that the scene does not save with all the cars on one of the streets at the intersection. After fixing this issue, I will upload a PR

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet-editor/pull/223
