### ISSUE TITLE
street-environment component should allow setting after load

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#303]
Steps to reproduce:
* Open up a 3dstreet scene in the 3dstreet editor, such as http://localhost:3333/#https://streetmix.net/kfarr/3/example-street
* Select environment layer (entity), and then scroll down to the street-environment component
* Change the preset value from day to night
* Right now observe that nothing changes visually in the scene

Instead, when changing the preset value from day to night...
* The scene should change to night without requiring reloading of the scene

Also, when changing the preset value from night to day...
* The scene should change to day without requiring reloading of the scene

**Comment by kfarr** [comment]
How to do this?
* use a-frame [component `update` lifecycle method](https://aframe.io/docs/1.4.0/core/component.html#update-olddata)
* if the value changes, and there was a previous value, then handle removing the old light entities and adding the new light entities appropriate for the settings change. Also update the value of the skybox asset to reflect the new setting.

**Comment by Algorush** [comment]
Added PR: https://github.com/3DStreet/3dstreet/pull/307



> How to do this?
> 
> * use a-frame [component `update` lifecycle method](https://aframe.io/docs/1.4.0/core/component.html#update-olddata)
> * if the value changes, and there was a previous value, then handle removing the old light entities and adding the new light entities appropriate for the settings change. Also update the value of the skybox asset to reflect the new setting.

I didn't make removing light and sky entities in each update call. Instead I change entity attributes when update is called. I think it's better. Tested, everything works well for now
