### ISSUE TITLE
fix issue with intersection-demo.json

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#306]
fix issue with [intersection-demo.json](https://github.com/3DStreet/3dstreet/blob/93c750768f046b670a56e421fa09a5bc05cfaecf/examples/json/intersection-demo.json)

to reproduce:
- use editor repo
- go to http://localhost:3333/index-mapbox-intersection.html
- save as 3dstreet json (that is how the file referenced above was made)
- reopen in 3dstreet viewer, then load the saved scene
- then click load 3dstreet editor to inspect the scene
- notice that there are some cars out of place and there are 2 street parents where there should only be 1 street

![image](https://github.com/3DStreet/3dstreet/assets/470477/244cbc23-43c8-4e04-82d0-b5abb58cccc4)

**Comment by Algorush** [comment]
PR to fix: https://github.com/3DStreet/3dstreet/pull/321
I'll also add this fixings to 3dstreet-editor

**Comment by kfarr** [comment]
closed by #321
