### ISSUE TITLE
better package save and load logic

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#313]
Create a new load-save-3dstreet component to include logic currently in index.html and json-utils.js.
- For example, recently to support a new loading feature both 3dstreet and 3dstreet-editor index.html needed to be updated
- Instead, this sort of logic should be in an a-frame component, probably added at the scene level
- instead of loading json-utils.js separately in index.html on 3dstreet and 3dstreet-editor repos, this should be integrated with 3dstreet index.js distribution and the built using the normal `npm run dist` process
- this new component (`save-load-3dstreet` for example) should serve the needs of both the viewer and the editor

**Comment by kfarr** [comment]
With some related discussions with @vincentfretin in https://github.com/3DStreet/3dstreet-editor/issues/212 it may make more sense to package save and load as an a-frame `system` instead of a `component`, since if it is a component it may not work while in editor mode with the scene paused

**Comment by kfarr** [comment]
v1 / mvp goal: specify a URL to a new component that will load a .3dstreet.json scene file

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/352
maked v1 for checking

**Comment by kfarr** [comment]
After 
https://github.com/3DStreet/3dstreet/pull/352
is complete we will use https://github.com/3DStreet/3dstreet/issues/390 to better package save / load functions
