### ISSUE TITLE
create notification component

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#317]
this component enables other components and the 3dstreet editor to send messages to the user about different activities in the application such as save or load status

it is probably easiest to use an off-the-shelf solution, I have researched this one that seems to do the job and has a reasonable license: https://github.com/caroso1222/notyf/

This component could have some settings that reflect the notyf object such as position, duration, etc.

This component would expected to be loaded only once at the scene level. Other scenes would interact with this component by either setAttribute to set property values on the component, and/or by calling a method such as AFRAME.scenes[0].components['notification'].sendMessage('yo');

installation options
* one "recipe" per their instructions, copy js and css into local file
https://github.com/caroso1222/notyf/blob/master/recipes/global.md
* in the 3dstreet repo, we could copy these can be located near other "viewer" styles, or even just integrated into the "viewer-styles.css"
*  Here is notyf css source,
https://github.com/caroso1222/notyf/blob/master/src/notyf.scss
can be added to https://github.com/3DStreet/3dstreet/blob/main/src/viewer-styles.css with a comment indicating where it came from and what it does
* And then js can be imported like other libraries in the repo saved locally such as https://github.com/3DStreet/3dstreet/blob/main/src/index.js#L7

(A future version of this component could include notification for VR / immersive model, especially useful when modifying scenes in VR and wanting confirmation of save event.)

**Comment by Algorush** [comment]
> This component would expected to be loaded only once at the scene level. Other scenes would interact with this component by either setAttribute to set property values on the component, and/or by calling a method such as AFRAME.scenes[0].components['notification'].sendMessage('yo');

Hi Kieran. Here you meant that other elements (not scenes?) can interact with the notifications component using setAttribute or sendMessage ?

**Comment by kfarr** [comment]
Yes this means to say that other entities, components, or js code from the editor may need to interact with this notification component

**Comment by Algorush** [comment]
What types of messages to make for notifications by default? It should be only one info type or more? There is success, error  by default or could be customized types.

**Comment by kfarr** [comment]
I think for now success (green) and error (red) is ok. In my experience sometimes there is also warning (yellow) and information (blue) but I would vote to wait to do those until another time when it's actually needed.

**Comment by Algorush** [comment]
> Yes this means to say that other entities, components, or js code from the editor may need to interact with this notification component

I did not understand a little how interaction should take place through setAttribute. I did it this way now:
AFRAME.scenes[0].setAttribute('notify','successMsg','hello')

**Comment by Algorush** [comment]
I noticed one peculiarity of using setAttribute. If it is called with the same data, then the update function of the component is not called. That is, the same message cannot be sent several times. It can be done using the component method

**Comment by Algorush** [comment]
PR: https://github.com/3DStreet/3dstreet/pull/319
Now we can call 2 types of messages - error and success. This can be done in two ways:
AFRAME.scenes[0].setAttribute('notify','successMsg','hello')
AFRAME.scenes[0].setAttribute('notify','errorMsg','error')
AFRAME.scenes[0].components.notify.successMsg('hello')
AFRAME.scenes[0].components.notify.errorMsg('error')

**Comment by kfarr** [comment]
@Algorush this is great! I just reviewed the PR with some requested updates

**Comment by kfarr** [comment]
closed with #319
