### ISSUE TITLE
In sparse mode, spawn fewer pedestrians

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#327]
In the loud bicycle game there are too many pedestrians even in sparse mode

Instead spawn half as many pedestrians as currently are spawned in a "sparse" sidewalk

**Comment by Algorush** [comment]
It's only in game or in 3DStreet too?

**Comment by kfarr** [comment]
in 3dstreet, then I'll update the game with the updated dist file (there are a few other bugfixes that we've done to bring over as well)

**Comment by Algorush** [comment]
Ok. And in other modes - normal and dense to leave the same?

**Comment by kfarr** [comment]
yes for now

**Comment by Algorush** [comment]
Done: https://github.com/3DStreet/3dstreet/pull/328
