### ISSUE TITLE
add title UI element to viewer

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#336]
From the 3dstreet viewer -- as a scene viewer, if the scene has a name, the scene name should be visible. the scene name should be accessible to viewer UI (also aframe scene) from all methods of loading scenes: 3dstreet json, streetmix, 3dstreet cloud

This should use: https://github.com/3DStreet/3dstreet/issues/335 such as:
`AFRAME.scenes[0].getAttribute('metadata').sceneTitle`

This UI element should update if the component property value changes (it may be set by means of editor or a loader)

Figma:
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=5482-23977&mode=design&t=0PBswixNj1m6p5ZK-4

Pasted png for convenience:
![image](https://github.com/3DStreet/3dstreet/assets/470477/ea867dd9-c130-4097-8b96-fef7dad97356)

The title should not be clickable, and clicks on the title should instead go to the 3d canvas as though the name wasn't there

brainstorming ways to solve this:
* another entity / component titleOverlay added to scene or viewer
* it creates a div with appropriate styling to be a title element. if the custom font is loaded great (what is that font again?) where is do we have a div with text? one of the buttons?

**Comment by Algorush** [comment]
So I can place the title update in the `update` function of the metadata component? I'll try to make the first version using a div, and the css property `pointer-event: none` for non-clickability

**Comment by Algorush** [comment]
> From the 3dstreet viewer -- as a scene viewer, if the scene has a name, the scene name should be visible. the scene name should be accessible to viewer UI (also aframe scene) from all methods of loading scenes: 3dstreet json, streetmix, 3dstreet cloud

So I can place the title update in the `update` function of the metadata component? I'll try to make the first version using a div, and the css property `pointer-event: none` for non-clickability

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/359
I've added a new div#sceneTitle to the end of the body for now. Perhaps later place it in another place

**Comment by kfarr** [comment]
@Algorush this looks really good!

Some feedback:
* may need to change location (to top) or justification (to left) later, but ok as-is for now

**Comment by kfarr** [comment]
@Algorush this looks really good!

Some feedback:
* metadata component should not have side effects of creating or updating a div, instead there should be separate component for that such as 'title-div' or 'metadata-title' which will also be on the scene entity. the new component will need to listen for an event from metadata component upon update, and it will need to emit an event. I can't remember offhand how to do this but I can help dig up some old examples if helpful.
* may need to change location (to top) or justification (to left) later, but ok as-is for now

**Comment by kfarr** [comment]
some more resources on event stuff:
* there are a few places already where we emit events https://github.com/search?q=repo%3A3DStreet%2F3dstreet%20emit&type=code
* and a few components where we listen for events like here: https://github.com/3DStreet/3dstreet/blob/5eaf1de87c1e0697fbcb1e298a3d007da4c5ccff/src/components/anisotropy.js#L11

**Comment by Algorush** [comment]
added commit with scene-title component and event emitter from metadata component

**Comment by kfarr** [comment]
excellent for v1!

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/pull/359
