### ISSUE TITLE
add environment option "Color"

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#337]
If blank chosen, then make the background color as defined in a new property named "backgroundColor" or similar. Default should be black. Lighting should remain the same as day.

To implement I think the skybox can be hidden and use the built-in scene property 'background' https://aframe.io/docs/1.4.0/components/background.html

**Comment by kfarr** [comment]
@Algorush I've been working on a related thing here: https://github.com/3DStreet/3dstreet/pull/365/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R398

**Comment by Algorush** [comment]
> @Algorush I've been working on a related thing here: https://github.com/3DStreet/3dstreet/pull/365/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R398

Will this branch be merged with main? So should I make a new branch based on 'beauty-shot?'

**Comment by kfarr** [comment]
@Algorush yes it will definitely be merged with main, might be good to wait on this for a second
https://github.com/3DStreet/3dstreet/issues/353

**Comment by Algorush** [comment]
I can't remember if I added a PR with a solution for the new Color option. I've added code for this in `environment-color` branch. But I don't see closed or open PR. Although I see that there is an `environment-color` branch

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/405

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/405
