### ISSUE TITLE
increase roughness of street surfaces to 0.8

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#340]
this could probably be achieved via adjusting mixins only, but may also need editing of the streetmix-parsers.js file

- street surfaces look too shiny with a default material roughness value of 0.5
![image](https://github.com/3DStreet/3dstreet/assets/470477/0edeac45-b109-4349-8706-433f7c66eebc)

- instead default material roughness value should be 0.8
![image](https://github.com/3DStreet/3dstreet/assets/470477/2ef82e87-a00c-415e-94ea-15af1c1514fd)

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/391

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet/pull/391
