### ISSUE TITLE
dont save JSON value in 'not-street' key in json-utils

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#344]
Fix json-utils. Make sure that the function to cancel saving the listed parameters in a JSON file works correctly

**Comment by Algorush** [comment]
I checked why the JSON property is not being deleted. Because the street component is stored as a string and its properties are not accessed during verification. So the question is: does it make sense to remove the entire street component, does it need to save?

**Comment by kfarr** [comment]
you're right, and I'd vote we let it go for now as it's not causing problems and there's plenty of storage space in these json blobs. closing

**Comment by Algorush** [comment]
@kfarr I wanted to ask did yet removed street component from the JSON output. Because I have not added it to removeProps in json-utils.js. Or did you do it in one of the PRs?
