### ISSUE TITLE
add brown box beneath building ground

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#362]
as part of this commit https://github.com/3DStreet/3dstreet/pull/365/commits/ea2c9e6d4b681c95b17ddf020bca16c9b256d598

related to https://github.com/3DStreet/3dstreet/issues/353

we added below-ground brown box under the street

now, this ticket is to build a brown box under the lots on both sides of street

**Comment by Algorush** [comment]
This should be done as a part of [beauty-shot](https://github.com/3DStreet/3dstreet/compare/beauty-shot) branch?

**Comment by kfarr** [comment]
close by https://github.com/3DStreet/3dstreet/pull/404
