### ISSUE TITLE
Rails extending past LRV or streetcar rails segment

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#363]
issue: streetcar or tram segment types have tracks that have an actual track glb cloned beneath it. at certain lengths part of the track glb extends beyond the intended end length of the street

see below image

Instead, we want segment with tracks to have the same length as other segments

suggested solution:
- use a long box with gray color and high reflectivity for each rail. Size it exactly as needed
- custom geometry: 2d shape that is extruded; custom geometry using "csg"; or other method

![image](https://github.com/3DStreet/3dstreet/assets/470477/e178cb84-d768-4d6d-9b65-c50daac01d8b)

**Comment by Algorush** [comment]
@kfarr could you tell please, how to reproduce this issue?

**Comment by kfarr** [comment]
yes sorry use this branch:
https://github.com/3DStreet/3dstreet/tree/beauty-shot

and open localhost:7001/#https://streetmix.net/kfarr/3/ or other streetmix path with a rail

**Comment by Algorush** [comment]
its looks nice with shadows. Added commit with new rails

**Comment by kfarr** [comment]
works great thanks!
