### ISSUE TITLE
viewer mode icons should be hidden when in editor mode

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#369]
([see failed attempt here](https://github.com/3DStreet/3dstreet/pull/368/commits/cd176ebcae2cf9082a5cb19df0be9a47b6d4fc96))

**Comment by kfarr** [comment]
chatgpt idea:

Certainly! The A-Frame editor, when opened, adds an `<aframe-inspector>` element to the DOM. We can use this information to detect when the editor is opened and closed.

Here's an A-Frame component that logs to the console when the A-Frame editor is opened and then closed:

```javascript
AFRAME.registerComponent('editor-listener', {
  init: function() {
    var sceneEl = this.el;

    var observer = new MutationObserver(function(mutations) {
      mutations.forEach(function(mutation) {
        if (mutation.addedNodes.length) {
          for (let i = 0; i < mutation.addedNodes.length; i++) {
            if (mutation.addedNodes[i].tagName === 'AFRAME-INSPECTOR') {
              console.log("A-Frame editor opened.");
            }
          }
        }

        if (mutation.removedNodes.length) {
          for (let i = 0; i < mutation.removedNodes.length; i++) {
            if (mutation.removedNodes[i].tagName === 'AFRAME-INSPECTOR') {
              console.log("A-Frame editor closed.");
            }
          }
        }
      });
    });

    observer.observe(sceneEl, { childList: true });
  }
});
```

To use this component, attach it to the `<a-scene>` tag in your HTML:

```html
<a-scene editor-listener></a-scene>
```

Now, when you open the A-Frame editor by pressing `ctrl + alt + i` and then close it, you should see messages in the console indicating the editor's state.

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/410
I did it via CSS. Its ok or no?

**Comment by kfarr** [comment]
@Algorush It's super excellent, thanks!
