### ISSUE TITLE
more street dining props randomly placed

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#375]
issue: the outdoor dining prop looks odd. Add more random props, not just 1 in the middle

Are there other segment types / variants that can use more randomization?

**Comment by Algorush** [comment]
> Are there other segment types / variants that can use more randomization?

I think it's the same for these elements? bike-lane, micro-mobility elements, drive-lane, self-driving car, bus-lane, parklet

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/413
I maked more randomly placed elements for these elements: bike-lane, micro-mobility elements, drive-lane, self-driving car, parklet. Now the scene looks much more interesting, especially with the animation. But I haven't fixed the grouped animation issue yet... I plan to finish it soon

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/413
