### ISSUE TITLE
fix elevation level support

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#388]
elevation level support for pedestrians, cyclists and other types of segments where the elevation level can be changed. Now this does not always work correctly

**Comment by Algorush** [comment]
Yes, I agree with everything. Streetmix supports changing the elevation level for sidewalks segments, bike paths and other similar segments

**Comment by kfarr** [comment]
Ok I'm going to do a try at this for next day or two and will ping you when ready to check it out

**Comment by Algorush** [comment]
I was going to do it myself. Because not long ago I did support elevation, but only the default value.

**Comment by kfarr** [comment]
I'm starting with this https://github.com/3DStreet/3dstreet/issues/396 first focusing on X axis, you're welcome to also start on this with the Y axis issue and then we can merge it together?

**Comment by Algorush** [comment]
it took a little longer. Almost finished. I checked elevation for all possible segment types.

**Comment by Algorush** [comment]
Now added commit with elevation support for all segments

**Comment by kfarr** [comment]
should be closed with https://github.com/3DStreet/3dstreet/commit/d467f149b20a9b3f0335f79d920828f08662e3c9
