### ISSUE TITLE
remove old street elements before add new elements

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#389]
in some cases, when adding a new scene, new street elements are added along with the old ones. Its better to clean up street and building elements before adding new ones. 
I added the code to remove the .street-parent element in this PR: https://github.com/3DStreet/3dstreet/pull/355/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R39
Still need to do this for .buildings-parent element

**Comment by kfarr** [comment]
@Algorush can you provide more detailed instructions to reproduce is issue of "new street elements are added along with old ones?"

**Comment by Algorush** [comment]
For example, when changing the street parameters in the editor on the right panel. 
![image](https://github.com/3DStreet/3dstreet/assets/32197767/c83407cb-6035-4a85-b81e-0782cc5de0e5)

**Comment by Algorush** [comment]
I described it a earlier here and solution for this: https://github.com/3DStreet/3dstreet/pull/355#issuecomment-1769717766

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/448

**Comment by Algorush** [comment]
I noticed one thing with the checkbox in the right panel interface. The switch doesn't work when I click on an area outside of the small circle. I created an issue in 3DStreet-editror with a description: https://github.com/3DStreet/3dstreet-editor/issues/374

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/448
