### ISSUE TITLE
use STREET global for notify

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#394]
Suggestion to create a new "subobject" from the Street global object.

Example usage:
* STREET.notify.successMessage('Things went well!')
* STREET.notify.errorMessage('Thing did not go well!')

Instead of:
```
      AFRAME.scenes[0].components['notify'].message(
        '3DStreet JSON file saved successfully.',
        'success'
      );
```

Why?
* simpler and logical syntax for Editor developers
* abstracts notification feature away from A-Frame component and instead use STREET global so that we can stub out later if needed

How:
- [ ] Add 2 new functions successMessage(<message as string>) and errorMessage(<message as string>) as under STREET.notify empty object
- [ ] Replace the legacy method to create notify messages and instead use this new method

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/414
