### ISSUE TITLE
Change structure of entities created by street component: BuildingsLeft, Segment1, 2, ... , Segment n, BuildingsRight

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#396]
Issue:
- Today, each segment "parent" is an entity with 0 0 0 location. Child entities have x and y translation that corresponds to the specific segment key/value pairs from streetmix json
- Instead, each segment "parent" should be an entity that reflects the x and y location of the specific segment, and children should be 0 0 0 (or otherwise adjusted using the parent's 'correct' location as its origin)

This would also solve this problem https://github.com/3DStreet/3dstreet/pull/387 and https://github.com/3DStreet/3dstreet/issues/388

Checklist:
- [x] In aframe-streetmix-parsers.js, modify segment-parents to have correct X placement
- [x] add updated titles per tree structure proposal below
- [ ] update parent relationships per tree structure proposal below
- [x] Reconcile Y placement if needed (wait for AG work)
- [x] rename / restructure buildings per below

## street parent tree structure proposal
Today it is:
```
3DStreet Layers
├── default-street (entity with street and street-loader components)
│   ├── street-parent
│   │   ├── segment-parent-0
│   │   ├── segment-parent-1
│   │   ├── segment-parent-2
│   │   ├── segment-parent-n
│   ├── buildings-parent
│   │   ├── ground-left
│   │   ├── block-left
│   │   ├── ground-right
│   │   ├── block-right
```

Instead I propose:
```
3DStreet Layers
├── Street: Harrison Street SB at 16th (use string from streetmix street name)
│   ├── Segment: Sidewalk (use segment type string)
│   ├── Segment: Bench (use segment type string)
│   ├── Segment: Tree (use segment type string)
│   ├── Segment: Parking (use segment type string)
│   ├── Segment: Drive Lane (use segment type string)
│   ├── Segment: n
│   ├── Block: ResidentialBuildings (use building type string)
│   ├── Block: ResidentialBuildings (use building type string)
```

**Comment by Algorush** [comment]
Yes, that's a good idea. 
But to support different elevations, `position.y` must be set to the element's parent (eg .pedestrian-parent) depending on the elevation. 
And by the way, it is enough to change `position.y` for .pedesrtian-parent and not for each pedestrian element, as now

**Comment by kfarr** [comment]
@Algorush great, that makes sense. I'll wait on Y for now and then you can review

**Comment by kfarr** [comment]
Almost there, buildings / lots could use a bit more work, here is current state, notice for things like fence or seawall they aren't properly nested under parent

![image](https://github.com/3DStreet/3dstreet/assets/470477/d07d5f0b-9e44-4008-b3ba-71495a8689be)

**Comment by kfarr** [comment]
good enough for now, let's do another pass when everything is deployed
