### ISSUE TITLE
refactor idea: streetmix-loader to create entity with street component

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#398]
Instead of having:
<a-entity id="default-street" street streetmix-loader set-loader-from-hash></a-entity>

An entity can be created that is the "streetmix loader" entity, and then it will create a child that has the actual street 

this street entity is "reactive" -- as a user you can change properties of the street component and it will update automatically, or at least destroy itself and recreate
--> this was Alex's original idea to delete `.street-parent`

**Comment by Algorush** [comment]
That is, abandon the streetmix-loader component? I'll see what options there are to do this.
