### ISSUE TITLE
Consider gltfpack'ing assets

### ISSUE THREAD

**Issue by donmccurdy** [3DStreet/3dstreet#4]
Optimizing the building (`scenesmall2.glb`) in the demo scene, you can drop it from 360 draw calls to 3 draw calls just by running it through [gltfpack](https://github.com/zeux/meshoptimizer#gltfpack) (although I had to un-draco-ify it first).

That will increase file size a bit (from 1.6mb to 2.6mb after gzip) but 1MB of that is just the billboard textures, which could probably be removed for streetmix's purposes. I thought adding Draco back to the asset afterward would get it back down to the same size, but for some reason it didn't help further.

I didn't test on any other assets in the folder, but gltfpack can be a pretty worthwhile tool a lot of the time. :)

**Comment by kfarr** [comment]
Finally getting to some optimization. I did the following:
- removed large billboard textures
- re-exported from blender as a non-compressed gltf / bin
- ran this through gltfpack with no compression enabled
- this creates a 6.7mb glb file, not including the small 78kb png texture (pre gzip), this is pretty big
- post gzip it is 1.4mb which seems quite reasonable given the size and complexity of the model
- for fun I tried default MESHOPT_compression which makes a 1.6mb file, also not bad but I don't see (out of the box) support for A-Frame gltf loading with this decoding option

Re GZIP and github pages:
- this project is served with github pages and normally github pages automatically gzips [common file types](https://webmasters.stackexchange.com/questions/56561/is-gzip-compression-available-for-github-pages)
- however checking using two different tools ([one](http://www.rexswain.com/httpview.html), [two](https://www.giftofspeed.com/gzip-test/)) neither confirms use of gzip
- I read that some users try to force github pages to use gzip by renaming their files to end in bmp, css, etc. but I don't think it is a good solutino
- it may be worth migrating this project to another host which allows for finer tuning of gzip settings on its own domain

I'm going to test performance impact next

**Comment by kfarr** [comment]
Testing street URL: http://localhost:8080/#https://streetmix.net/kfarr/34

before: 283998 tris, 783 draw calls
after: 283998 tris, 418 draw calls (reduced by 365)

Next to test in VR - is there a noticeable framerate or performance change?

**Comment by kfarr** [comment]
- Not a huge noticeable impact on frame rate in quest, but every bit is helpful and there are many more assets to optimize
- Hesitant to push an update that triples download size but it could be a motivation to continue to simplify the asset as well as find an alternate host that gzips gltf/glb files

**Comment by donmccurdy** [comment]
Hm, yeah gltfpack benefits a lot from gzip, in this case I don't know if it's worthwhile without it. It's too bad GitHub pages doesn't support that better. Maybe we could convince them to add `.glb` to the automatic gzip list, or to support pre-compressed assets (https://github.community/t5/GitHub-Pages/Support-for-pre-compressed-assets-and-brotli-compression/m-p/22055).

**Comment by donmccurdy** [comment]
Worth a try: https://github.community/t5/GitHub-Pages/Support-for-gzip-on-glb-3D-model-files/m-p/55767#M2962

**Comment by kfarr** [comment]
Thanks, also left a comment on that thread with relative file size comparisons from this project.

I also tried taking the gltfpack optimized mesh output and feeding that back into draco using gltf-pipeline. While it didn't throw an error it definitely doesn't look right: 
![image](https://user-images.githubusercontent.com/470477/80330381-e06bf780-87f9-11ea-8282-5412fc4f02bc.png)

It seems like MESHOPT will soon be a standard part of glTF spec? Hopefully then three.js / A-Frame will follow suit to support that out-of-the-box in the coming months / year?
https://github.com/KhronosGroup/glTF/pull/1702/commits

A gzip'ed output of gltfpack and/or MESHOPT seem to be the best balance of size, performance and quality.

I will also try combining the meshes together in Blender manually before exporting draco gltf and maybe that will help with draw call issue until gzip or meshopt is available for pages / a-frame.

**Comment by kfarr** [comment]
My attempt to make a meshopt decoder work with A-Frame gltf loader component did not work.

A-Frame uses threejs 111.6. This appears to require threejs 114: 
https://github.com/zeux/meshoptimizer/blob/master/demo/index.html

Attaching work in progress of the gltf-model component modified to decode meshopt geometry as well as a glb file compressed with meshop gltf extension. Assumes this custom [GLTFLoader.js](https://github.com/zeux/meshoptimizer/blob/master/demo/GLTFLoader.js) is loaded beforehand and that [meshopt_decoder.js](https://github.com/zeux/meshoptimizer/blob/master/js/meshopt_decoder.js) is also available in scope.

Work in progress: [meshopt_aframe_WIP.zip](https://github.com/kfarr/streetmix3d/files/4569490/meshopt_aframe_WIP.zip)

Marking as blocked. To unblock, try again when A-Frame includes threejs 114+ or when MESHOPT gltf extension is included in threejs / A-Frame out-of-the-box.

**Comment by kfarr** [comment]
No longer blocked, A-Frame master includes three 115

**Comment by kfarr** [comment]
marking done as we are redoing our pipeline in a different repo https://github.com/3DStreet/3dstreet-assets
