### ISSUE TITLE
logo doesn't show when exporting image from editor mode

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#415]
see https://github.com/3DStreet/3dstreet/pull/409#issuecomment-1826145952

**Comment by Algorush** [comment]
I haven’t yet understood why the screenshot appears without a logo when using 3dstreet-editor.js from 3dstreet.app. But if I use the build with master branch of 3DStreet-editor then everything works well

**Comment by Algorush** [comment]
Now with new release of 3DStreet-editor logo is showing in Editor mode

**Comment by kfarr** [comment]
yes confirmed working!
