### ISSUE TITLE
bug: 3dstreet logo is too tall in screenshot overlay

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#424]
the logo is too tall
![image](https://github.com/3DStreet/3dstreet/assets/470477/873fe5a5-08b6-4deb-b766-f2820a3c04b6)

it's probably my fault again, I made this change, although I tried to increase x and y by the same proportion so not sure...
https://github.com/3DStreet/3dstreet/commit/afe95d81f81eb4a5578d4a83ed7b375eac00a6ab

**Comment by Algorush** [comment]
Yes, when logo image came from svg, it has size 135x23 instead of 135x43 as is the case with the img element (there is top and bottom padding). And therefore we need to change the scale of canvas (from svg) not to 270x86 but to 270x46.

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/432
