### ISSUE TITLE
characters are gathered together

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#427]
characters are not distributed along the walking path.
![image](https://github.com/3DStreet/3dstreet/assets/32197767/eeed894d-3437-462b-a35d-1243a7c54e55)

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/431
Oops. Looks like I removed positions for non-animated characters in one of the previous PRs

**Comment by kfarr** [comment]
closed by #431
