### ISSUE TITLE
support the ability to produce something similar to this target image

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#437]
![image](https://github.com/3DStreet/3dstreet/assets/470477/31600da8-1fe0-439b-89d2-271e06fadb1f)

some of the parts needed for this:
- emission from the buildings -- is this a texture issue (blender), or a technical issue (a-frame / three.js?)
- soft or low opacity shadows (since streetlights are not much brighter than the moon, stars and ambient light pollution) -- This may be doable with some ambient light + moon light. In fact, this may already be supported in the night preset already.
- bloom on lantern bulbs --> bloom not supported in a-frame. either drop requirement or use lens flare hack from signals glitch.
- the use of crosswalks could be achieved with an intersection that only has sidewalks on north and south sides

**Comment by Algorush** [comment]
Great, I think we can make a similar picture using Three.js and post-processing. Should this be high quality render for one picture/screenshot or real-time rendering option?
