### ISSUE TITLE
can't change the parameters of the street component for a scene loaded from JSON

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#459]
After loading the scene from JSON, the `#default-street` element does not have a street component, meaning we cannot change its properties such as showAnimation, sowGround, ...

**Comment by kfarr** [comment]
As a user, I wish to change street and `streetmix-loader` parameters. Including the option to regenerate the street from streetmix or change the URL to another street

**Comment by Algorush** [comment]
I propose the following solution to make it possible to change the parameters of the `street` and `streetmix-loader` components after loading a scene from a JSON file. 
1. avoid renaming `street` to `not-street` and `streetmix-loader` to `not-streetmix-loader`. 
2. Don't call init/update methods of the `street` and `streetmix-loader` when loading scene with these components from JSON.
To do this I will add a global variable:
`STREET.sourceType = jsonFile/streetmix/streetplan.`
