### ISSUE TITLE
research ticket - convert street segment to custom UVs for gltf export

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#467]
Issue: some third-party gltf loaders do not support `KHR_texture_transform` module, therefore rendering incorrectly a 3DStreet scene in the target application. This produces critical error for the user that result in misrepresentation of street layout.

Instead: 
- Consider changing to no longer use texture material repeat three.js feature, and instead convert the box geometry material used for segments to have custom uv settings that match the behavior of texture material repeat feature since it is not supported by third-party.

Suggest to spend a few hours to try doing this. Chat gpt has some ideas, you can ask this custom GPTs bot trained on three.js: https://chat.openai.com/g/g-jGjqAMvED-three-js-mentor

**Comment by Algorush** [comment]
Its not possible to do this with box segments. There is no such option to repeat the texture on each segment. But I found another way (with UVs settings) and will implement it after google 3D tiles work

**Comment by kfarr** [comment]
Yes agreed custom UV settings will be needed, here is an example: https://chat.openai.com/share/b123f352-6358-491d-8f90-0f8993a94d45

**Comment by kfarr** [comment]
see https://github.com/3DStreet/3dstreet/issues/467
