### ISSUE TITLE
saving a scene with ocean results in error when re-opening

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#469]
steps to reproduct:
- go to https://3dstreet.app/#https://streetmix.net/kfarr/3/example-street (as of writing this ticket this street has ocean as the building type on both sides)
- give it a unique title
- save
- load another street from the open modal
- then reload the street with that unique title
- note that the ocean does not animate and there are error messages in console
![image](https://github.com/3DStreet/3dstreet/assets/470477/ae2d836a-9bd6-4b50-8e95-523099a187de)

in local dev mode the error message is big
![image](https://github.com/3DStreet/3dstreet/assets/470477/aa14b4cd-639e-4c0d-bb15-33e1ae2a0dba)

when saving / loading scenes without the ocean there are not these error messages

**Comment by Algorush** [comment]
This error was resolved by this PR, I had commented about it here: https://github.com/3DStreet/3dstreet/pull/440#issuecomment-1894692233

**Comment by kfarr** [comment]
this was resolved, however ocean is not animated upon reload. That's ok and we can deal with that later
