### ISSUE TITLE
tram and bus stop are too large

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#471]
- setting scale to 0.8 0.8 0.8 for both tram and bus-stop mixins seem to be closer to reality, and the tram wheels correctly match the rail gauge width after transformation
- thanks @dmarcos for calling this out today :)

question:
- should this resize be done in 3d model source and glb dist or in the app via scale? it should be done in the original model
- should we do 0.8 or should we look up the actual values for these objects?
- the train is a siemens LRV4 Width 104.32 in 2650 mm 
 (2.65m) https://assets.new.siemens.com/siemens/assets/api/uuid:02801dad-5a01-478c-beb0-8ef209289802/SIE-RS-SanFran-S200-Sheet-10-9-19-v2.pdf

**Comment by gnansai** [comment]
Hi @kfarr 
1. I checked the dimensions of the Light Rail Vehicle in Blender. I might have to adjust the model a little to match the real world dimensions.
![image](https://github.com/3DStreet/3dstreet/assets/25223402/b9a3e5f2-fc1b-4caf-81df-1373aedec2f7)
![image](https://github.com/3DStreet/3dstreet/assets/25223402/d598ded3-0fca-424f-a002-ce57a5d8bd9b)

**Comment by gnansai** [comment]
My Suggestion would be, We try to match this model with real world dimensions.
@kfarr Do let me know what your suggestions on this.

**Comment by kfarr** [comment]
@gnansai yes I agree to match this with real world dimensions, thank you for researching them above. I would say yes go ahead with those changes if you haven't already

**Comment by gnansai** [comment]
Hi @kfarr 
I have updated the LRV similar to real-world dimensions. 
I have uploaded the latest version of the model here
https://github.com/gnansai/3dstreet-assets-dist/tree/5271bb5b9a0c5706018c3d5682d49975433bbc24/sets/light-rail-vehicle/gltf-exports/draco
![image](https://github.com/3DStreet/3dstreet/assets/25223402/239fb26c-9b28-4d73-a3f3-f05f7d7f6f5d)
![image](https://github.com/3DStreet/3dstreet/assets/25223402/da2fb49a-c37d-4cbb-a314-60c9bb0afa9f)
![image](https://github.com/3DStreet/3dstreet/assets/25223402/16d0566c-6010-4ee6-a2ab-b53084abe457)

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/559
