### ISSUE TITLE
sometimes an svg layer will load 90º incorrect on one rotation axis

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#479]
- ~~issue 1 svg file always loaded with grass texture even when user changes material and saves~~ RESOLVED
- issue 2 if a user attempts to remove material src and saves, then rotation is incorrect sometimes upon reloading

here's what it should look like as I saved it:
![image](https://github.com/3DStreet/3dstreet/assets/470477/e311a29b-c451-4883-9c9a-8df8a0184c3d)

here's what it looks like when I re-open it:
![image](https://github.com/3DStreet/3dstreet/assets/470477/cb8c0438-c2e1-45ce-a3ce-92d8f9bf82bb)

this URL:
https://dev-3dstreet.web.app/#/scenes/cc5eeac7-b81e-4c78-95f9-3259ee3189ea.json

Note rotation values in "bad" version of 0 180 180 vs. "good" rotation values of 90 0 0
![image](https://github.com/3DStreet/3dstreet/assets/470477/6b2ff65f-8e20-48da-8f2f-c22bf3ac8cf0)

**Comment by kfarr** [comment]
Some thoughts:
* For issue #1 I'm guessing the grass texture in the component is overriding the user decision to remove a texture. Maybe it is better for the component to NOT add any material or only if a component property is passed to indicate that the material should be set
* For issue #2 I am very confused as to how that happens. I can do a dump of the scene JSON before / after which might help diagnose

**Comment by kfarr** [comment]
For issue # 2 here is how to reproduce reliably:
- After importing the svg, then change the Z scale to 0.01 and change the Y position to -0.1, then save
- Then upon reloading it has incorrect rotation parameters

**Comment by kfarr** [comment]
For issue # 2 I notice that there are a few attributes that are "hard coded" into the component:

https://github.com/3DStreet/3dstreet/blob/main/src/components/svg-extruder.js#L27-L29

* Likely this is the cause of the user selected material settings not being reflected
* Unsure why but perhaps the competing attempt to set different scale values results in odd rotation behavior

**Comment by Algorush** [comment]
About point 1. If do not set the material in component, then the material component will not be seen in the Editor and user couldn't change it. I made the default grass and saving/loading works well. The user can remove the texture, if necessary, add color, etc.

**Comment by Algorush** [comment]
I can't reproduce issue 2. I was trying my scene and your scene also. I added check for scale editing also before editing scale to 0.05... So now scale can be saved correctly in JSON. Maybe its better to make default scale attribute to component?

**Comment by kfarr** [comment]
>  I made the default grass and saving/loading works well. The user can remove the texture, if necessary, add color, etc.
@Algorush where can I find these changes on a branch or PR?

**Comment by Algorush** [comment]
Sorry, I fogot to make a PR. https://github.com/3DStreet/3dstreet/pull/480

**Comment by kfarr** [comment]
Let's celebrate that the first issue has been resolved, yay thank you! The second is not, will write up more soon.

**Comment by kfarr** [comment]
Here is an example of rotation of svg entities being inconsistent as I reload the same scene over and over again:

https://github.com/3DStreet/3dstreet/assets/470477/c24b9c5c-25eb-4af7-a1d1-b6043dd229ed

**Comment by kfarr** [comment]
One hypothesis is that there are race conditions going on with rotation being set multiple times. For example perhaps the svg is rendered at rotation x1 y1 z1 in three.js and then a-frame attempts to apply a transformation for rotation, but maybe sometimes a-frame applies the transformation before the svg rotation is applied or vice versa resulting in inconsistent conditions

**Comment by kfarr** [comment]
Note the similarity to the error in this case: https://github.com/nytimes/aframe-loader-3dtiles-component/issues/34

Sometimes the tiles were 90º incorrect, sometimes correct. Again a situation where perhaps three.js is doing its own thing and maybe a-frame sometimes applies a transformation before the other or vice versa

**Comment by kfarr** [comment]
maybe remove this line?
https://github.com/3DStreet/3dstreet/blob/main/src/components/svg-extruder.js#L80

and instead set rotation using a-frame component property?

**Comment by Algorush** [comment]
yes, now I see it. The rotation transformation is applied twice when loading a scene. The first time the rotation is applied is from the component code, and the second is from the saved JSON data

**Comment by Algorush** [comment]
After last PR with fixes it seems that rotation issue is gone. But for previous saved JSON scenes using `svg-extruder` to work correctly, you need to manually remove the `scale` and `rotation` values for extruded element. Or change them in the editor - scale: 1 1 1, rotation: 0 0 0. Now these values ​​are set for the `geometry` before adding it to the Mesh. Also made centering geometry more efficient.
There is one problem - when changing the `depth` parameter for `svg-extruder`, the material disappeared... I don’t know yet how to fix this. It might be best to disable this option for now.

**Comment by kfarr** [comment]
resolved by #482
