### ISSUE TITLE
new scene function - reference layer is not removed when loading new scene

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#485]
If open a scene with a reference layer, for example with a mapbox component, then if then load another scene from JSON, the reference layer of the old scene remains in the new scene

**Comment by kfarr** [comment]
I propose to have a "new scene" function that is called before loading a new scene, and will also be a user interface button that allows a user to create a blank new 3dstreet scene.

A blank scene should have all the base layers as though loading from index.html without a scene.

The new scene function should also reset metadata of scene id and title to empty strings.

On the editor, we have 4 places to call this "new scene" function:
- when loading a 3dstreet scene from cloud via open modal
- when loading a 3dstreet scene from upload json via open modal
- when loading a streetmix street from open modal
- when the user presses a "new" button in the user interface

**Comment by kfarr** [comment]
@Algorush is this ready for review?

**Comment by Algorush** [comment]
yes
