### ISSUE TITLE
issue: cannot open streetmix url with unsupported segment variants

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#488]
`Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

Error:
https://3dstreet.app/#https://streetmix.net/kfarr/129/error-proposed-owens-st

Not an error:
https://3dstreet.app/#https://streetmix.net/kfarr/130/proposed-owens-st

The issue seems to be related to drive lane variants that are not supported.

Instead, unsupported variants should be handled gracefully -- they should do best effort to render the scene

In best case there is a nice error message for user in yellow warning notification that says "Street imported from Streetmix but some segment variants are not supported." or at least a console log warning for debugging purposes

**Comment by Algorush** [comment]
I was mention about similar issue:https://github.com/3DStreet/3dstreet/issues/464
I think it would be helpfull to have a list with supported segment types and variants also

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/495
