### ISSUE TITLE
svg extrude bevel uses bevelColor instead of color when bevelEnabled is false

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#504]
instead svg extrude bevel should use `color` instead of `bevelColor` when bevelEnabled is false

in this example the yield teeth are white (per `bevelColor`) but should be red (per `color`) 
![image](https://github.com/3DStreet/3dstreet/assets/470477/f89b74f8-1523-421d-a408-393bff06de79)

https://3dstreet.app/#/scenes/206e81b2-ef21-403d-98e8-e4103f152a74.json

**Comment by Algorush** [comment]
what if I make the attribute names like this?

- top element color - topColor
- main element color - color
- src for the top element - topSrc
- src for main - src
