### ISSUE TITLE
fix outstanding things after combining repos

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#524]
Things to fix
- [x] dist folder https://github.com/3DStreet/3dstreet/issues/574
- [x] README
- [x] remove legacy folder / package-lock.json inside
- [x] transfer issues from 3dstreet-editor repo into editor
- [x] remove extra .html examples / demos that are out of date
- [x] "ARCHIVE" the `3dstreet-editor` repo to make it read only
- [x] remove old json utils

**Comment by vincentfretin** [comment]
For dist folder, meaning copying files from public folder to dist and deploying dist to firebase and as well make index.html a resource handled by webpack so the url to dist files are versioned will allow to lazy load react components and libraries. Some work was done in https://github.com/3DStreet/3dstreet-editor/pull/358 but was probably blocked by the webpack config at the time.
