### ISSUE TITLE
implement `street-geo` component in Editor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#526]
To add street-geo support to the Editor, first
* Add Entity panel - there should be 2 new "cards" in the add entity panel -- one for Mapbox 2D Map and one for Google 3D Map
* As a user I can click on one of these and the scene will be updated to either add a new street-geo component if none exists, or modify it to match my expectation to enable or disable a chosen map
* There should only be 1 instance of the street-geo component in any scene

How to display these in the scene / disable editing:
* Properties panel should be disabled for entities with "autocreated" class. 
* Those objects should not be selectable in most cases -- do we use "data-ignore-raycaster"

The street-geo component should be at the root. Use "Reference Layers" entity but instead rename this display name to "Geospatial Layers."

### Other questions:

> How does a user remove a map?

Select the map layer and delete it? if so, do we need to update the parent to reflect that the child was deleted? we can listen on the street-geo component if the child is removed, and then update the maps array to reflect the maptype that was just removed.

> How does a user change the location of the maps?

This is a custom UI modal to allow for the selection of a location.
https://www.figma.com/design/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=6547-169536&t=bbv3JutJgAqMAqjd-4

This modal has already been started here:
https://github.com/3DStreet/3dstreet-editor/pull/422/files#diff-105d9950bd2cd9c78fdb5f036fdfe8972f9e5e8ec1e21c8f7f89af92302ae93c

Note that we want to remove billing (pay wall) from this flow for the first version, we can add that later.

**Comment by Algorush** [comment]
I discovered that the `aframe-loader-3dtitle-component` is not the latest version. And it looks like the version used is not from the 3DStreet repository: https://github.com/3DStreet/aframe-loader-3dtiles-component
by looking at the list of attributes and the code of the component in the minified version. Also 3dtiles are not updated when switching to Editor. No copyrightEl attribute and other things

**Comment by kfarr** [comment]
Yes you're right, it will all need to be updated and the working changes that we used for the glitch demo ([like this one](https://maps-and-splats.glitch.me/)) brought to this repo

**Comment by Algorush** [comment]
So addtitional tasks here: 
- update aframe-loader-3dtitle-component dist from this repo: https://github.com/3DStreet/aframe-loader-3dtiles-component. Make new dist there first
- transfer the working changes from glitch demo

**Comment by Algorush** [comment]
> How to display these in the scene / disable editing:
> 
> * Properties panel should be disabled for entities with "autocreated" class.

That is, add a new feature in the Editor to hide the properties panel for entities with "autocreated" class.

**Comment by kfarr** [comment]
> > Properties panel should be disabled for entities with "autocreated" class.
> That is, add a new feature in the Editor to hide the properties panel for entities with "autocreated" class.

No we do not want to hide it. We definitely want to show it but to make it disabled (user cannot edit it). Eventually user will have the ability to determine if an item should switch to be a manual object instead of autocreated

**Comment by Algorush** [comment]
> > > Properties panel should be disabled for entities with "autocreated" class.
> > 
> > 
> > That is, add a new feature in the Editor to hide the properties panel for entities with "autocreated" class.
> 
> No we do not want to hide it. We definitely want to show it but to make it disabled (user cannot edit it). Eventually user will have the ability to determine if an item should switch to be a manual object instead of autocreated

Does aframe-inspector have an option to disable the ability to edit parameters? 
If not or if it has, what option is better to implement:
1. Hide the button to open the right panel
2. Leave the button and the ability to open the panel. Leave the `position, rotation, scale` fields for editing. And make the rest uneditable
3. Or maybe another option?

**Comment by kfarr** [comment]
@Algorush let's ignore this issue for now, made a separate ticket for it: https://github.com/3DStreet/3dstreet/issues/539

**Comment by Algorush** [comment]
I'll store lat, long, height in a global STREET.coords ?

**Comment by kfarr** [comment]
@Algorush I like the idea, but can we just put this in metadata instead of a new thing? Like how we fetch title?

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/540
