### ISSUE TITLE
The saved JSON scene is not loading correctly

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#534]
Scene before saving: 
![image](https://github.com/3DStreet/3dstreet/assets/32197767/9af30d23-bc51-48b3-ba11-1eab1f69be20)
Scene after loading: 
![image](https://github.com/3DStreet/3dstreet/assets/32197767/3384c269-b100-480d-ad4f-5a5940f03312)

Perhaps the reason is as follows. I noticed in the dev version that some of the vector values ​​were saved differently: instead of `rotation: '0 90 0'` it is now saved as `rotation: 'x:0 y: 90: z: 0'`. Also some of the material parameters: instead of `offset: 0.415 0;` became `offset: x: 0.415; y: 0;`
I'll look in more detail tomorrow

**Comment by kfarr** [comment]
@Algorush I think this is just another case of "do not save materials" and instead we should only be saving in wrapper components.

**Comment by Algorush** [comment]
> I noticed in the dev version that some of the vector values ​​were saved differently: instead of `rotation: '0 90 0'` it is now saved as `rotation: 'x:0 y: 90: z: 0'`. Also some of the material parameters: instead of `offset: 0.415 0;` became `offset: x: 0.415; y: 0;`

If you save the same streetmix scene via localhost and via 3dstreet.app, you can see the difference when comparing JSON:
![image](https://github.com/3DStreet/3dstreet/assets/32197767/39dea814-8d7e-472c-8799-d27ba130ca3b)
![image](https://github.com/3DStreet/3dstreet/assets/32197767/bdd50ff2-e269-42ef-9e25-baddbe5b2e80)
