### ISSUE TITLE
Notify user when loading streetmix failed because of 503 Service Unavailable

### ISSUE THREAD

**Issue by vincentfretin** [3DStreet/3dstreet#549]
When I loaded the default streetmix scene, I ended up with an empty scene not knowing why.
In the console I got the error 
`https://streetmix.net/api/...net::ERR_FAILED 503 (Service Unavailable)`
The service was down for 5 minutes.

There is probably a missing check for status code when you download the streetmix file to properly show a message to the user that the download failed. I don't know where is the code that downloads the streetmix file.

In javascript with fetch, when status code is different than 20x there is no exception raised like it's the case Python for example.
You need to check for res.ok and raise an exception yourself, for example
```js
fetch(url, headers)
  .then((res) => {
    if (!res.ok) throw Error(res.statusText);
    return res.blob();
  })
```

**Comment by kfarr** [comment]
related https://github.com/3DStreet/3dstreet/issues/274#issue-1690366802

**Comment by kfarr** [comment]
closing duplicate
