### ISSUE TITLE
In geomodal, pressing the letter h in a place search it will close the modal

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#562]
This is caused by the default help keyboard shortcut `h`
 → the same issue happened once before with a title rename feature, the workaround was to use `isExtraCloseEnabled` see:
https://github.com/3DStreet/3dstreet-editor/pull/312/commits/f61e12060a152d68c7b871fca0a9d3d54c4df258#diff-3ca8a64d250a8f7449f132f6fac892d85418d0d3a642f95ca46fcbd69b6ab65c

**Comment by Algorush** [comment]
I did not quite understand. Why we need this code:
`extraCloseKeyCode={72}`

Is this necessary so that when user press `h`, all windows will close and the help window will open?

**Comment by kfarr** [comment]
> I did not quite understand. Why we need this code: `extraCloseKeyCode={72}`
> 
> Is this necessary so that when user press `h`, all windows will close and the help window will open?

it does nothing of value, should only be on the help modal, we should remove it and is resolves this issue

**Comment by Algorush** [comment]
I noticed that if I remove this line, GeoModal does not close when I click on Cross in the upper right corner... I’m looking for the reason

**Comment by Algorush** [comment]
This is now fixed after street-geo-editor merged
