### ISSUE TITLE
posthog runtime errors

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#563]
had to disable posthog for local dev because it raises uncaught runtime errors. perhaps the official react version would be better?

![image](https://github.com/3DStreet/3dstreet/assets/470477/f562b92e-71ee-44c3-8fd9-fc7e5c4a42ad)

**Comment by rahulkgupta** [comment]
<img width="1432" alt="Screenshot 2024-06-06 at 8 07 16 PM" src="https://github.com/3DStreet/3dstreet/assets/610372/3fbd2fb1-31fe-406f-9c05-740d13d6a5f0">
<img width="389" alt="Screenshot 2024-06-06 at 8 08 06 PM" src="https://github.com/3DStreet/3dstreet/assets/610372/1171a39c-835e-49ec-a414-1d12362ac454">

very odd. im moving things around and clicking and not able to repro. I'm on `add-posthog` branch and am running things with `npm start`

**Comment by vincentfretin** [comment]
The collecting data for the session replay feature seems to be rather aggressive.
```
sessionrecording.ts:789 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'd'
    |     property 'components' -> object with constructor 'Object'
    |     property 'position' -> object with constructor 'n'
    --- property 'el' closes the circle
    at JSON.stringify (<anonymous>)
    at e.value (sessionrecording.ts:789:27)
    at emit (sessionrecording.ts:683:22)
    at ht (index.js:108:57)
    at le (index.js:138:9)
    at He.e.mutationCb (observer.js:731:19)
    at e.emit (mutation.js:308:18)
    at e.processMutations (mutation.js:107:18)
```

in sessionrecording.ts:789:27
`const size = JSON.stringify(event).length`
it stringify the event probably the mouseenter or click event on the canvas and try to serialize the cameraRig entity where we have the cursor-teleport component, and an aframe entity has object3D and the again el a reference to the aframe entity.

**Comment by vincentfretin** [comment]
We should see if we can just disable the session replay feature.

**Comment by rahulkgupta** [comment]
gotcha, will try the other way. session replay is a key feature IMO to understand how the user is using the product

**Comment by vincentfretin** [comment]
That should be fixed by https://github.com/PostHog/posthog-js/pull/1230

fyi the issue was triggered by this code
https://github.com/3DStreet/3dstreet/blob/01929dd62c39eed52dc79b41a1f7489b7c29fad6/src/components/screentock.js#L31-L43
with the `removeAtttribute('cursor-teleport')` that is called to take a screenshot when you click on Share button.
