### ISSUE TITLE
bounding box hover area does not match target geometry

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#588]
As a user attempting to select segments of a street that has been rotated to match real world conditions, I expect the hover bounding box to match the segment area.

The hover area bounding box appears to be oriented on a central axis (axis aligned bounding box) instead of a bounding box oriented to the geometry (oriented bounding box)

![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/c38d4791-4429-4aa9-87e2-028fce5eb833)

considerations:
* check out https://threejs.org/docs/#examples/en/math/OBB
* is obb used in a-frame inspector already? three.js editor?

**Comment by vincentfretin** [comment]
THREE.OBB is available in aframe 1.5.0 because it's used now for the new obb-collider component.

**Comment by vincentfretin** [comment]
Nothing to do with OBB really.
The interesting part is this https://github.com/aframevr/aframe/blob/11abbb2a8546e36fc3dba20ecb112b75ea2b29c8/src/components/obb-collider.js#L141-L164
