### ISSUE TITLE
triage 3dtiles not loading when added mid-session

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#603]
Sometimes as a user who selects google 3d tiles, they do not load.

No user visible error. Sometimes it might appear and just be taking a while to load, sometimes it never loads.

To reproduce:
- Choose lat/long
- Choose mapbox
- Then choose google3d
- the google 3d tiles do not appears (sometimes)
- Workaround: save the scene. Then reload, then the google 3d tiles appear correctly (usually)

**Comment by Algorush** [comment]
Yes, I also noticed this behavior. I can study the reasons and fix it

**Comment by Algorush** [comment]
the reason was that the `data-no-pause` attribute only works when navigating from Viewer->Editor. Therefore, it was necessary to add a `play` method call to the element with `loader-3dtiles` to start loading tiles if we are in the Editor

**Comment by kfarr** [comment]
closed by #624
