### ISSUE TITLE
add image, splat, intersection layers

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#613]
The existing image, splat, intersection components should be available in the add layer panel

- [x] (1) Geo - street-geo maptype: google3d - (MBES / TREAT)
- [x] (2) Additional Streetmix Street - to have multiple sections (MBES)
- [ ] (3) Image - to see my work (TREAT)
- [ ] (4) Splats - (TREAT) street-splat URL specified
- [x] (5) Gltf - to add custom objects (MBES)
- [x] (6) SVG - to add custom geometry to my scene (MBES)
- [x] (7) 3DStreet models. I will describe the questions for discussion in a separate section below
- [x] (8) QR anchor (street-qr-anchor)
- [ ] (9) Intersection - to allow for automatic intersection
- [x] (10) MapBox - (MBES) street-geo maptype: mapbox2d

**Comment by Algorush** [comment]
Does Image mean screenshot or something else?

**Comment by Algorush** [comment]
I'm making an auto-intersection component now from this issue: https://github.com/3DStreet/3dstreet/issues/438. I'll write my thoughts there.

**Comment by kfarr** [comment]
> Does Image mean screenshot or something else?

image is a plane that accepts a material src path to jpg or png file

example in this scene with image 1914 sanborn fire insurance layer

https://dev-3dstreet.web.app/#/scenes/6a342577-e482-4d90-81b5-44ae3645a1ff.json



![Image](https://github.com/3DStreet/3dstreet/assets/470477/45d204b9-93dd-4829-969d-00705951ca03)

**Comment by Algorush** [comment]
About splat layer. Services that generate splats, such as [poly.cam](poly.cam), provide them in a variety of formats, including `gltf`.
Then, in fact, we already have the opportunity to add splat to the scene through the `gltf` import function on Pro Layers.
My question is what capabilities should Splat Layers provide and look like?

**Comment by kfarr** [comment]
Hey @Algorush a few updates

> I'm making an auto-intersection component now from this issue: https://github.com/3DStreet/3dstreet/issues/438. I'll write my thoughts there.

To keep things simple, for this first ticket #613 let's just have a default intersection placed without any input field; then we can support dynamic editing of intersections, and then after that we can worry about automation

> My question is what capabilities should Splat Layers provide and look like? Also what's mean "street-splat URL specified"?

To keep it simple, it should just accept a splat file like line 59 here:
https://glitch.com/edit/#!/maps-and-splats?path=index.html%3A59%3A7

So you can have an input modal popup and use this URL as the default value for src property of gaussian-splatting component:
https://cdn.glitch.me/f80a77a3-62a6-4024-9bef-a6b523d1abc0/gs_Bioswale3_treat.splat?v=1711771503321

**Comment by Algorush** [comment]
> To keep things simple, for this first ticket #613 let's just have a default intersection placed without any input field; then we can support dynamic editing of intersections, and then after that we can worry about automation

Ok got it. I almost made the automation version

**Comment by kfarr** [comment]
added intersection, others come later
