### ISSUE TITLE
create a basic arrow / hand toolbar

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#615]
example UI:
![Image](https://github.com/3DStreet/3dstreet/assets/470477/3701b83e-1258-47c6-9365-9043b683e8fe)

current behavior is arrow, and is default
new behavior is hand
- when selected the cursor turns into an open hand to indicate grabbing
- in this mode the raycaster is off, a user cannot select items

implementation thoughts:
- might be implemented in EditorControls.js
- keyboard shortcut "q" for hand mode? (since "w" is current keyboard shortcut for select / move; "e" is select / rotate; etc)

**Comment by vincentfretin** [comment]
Not sure if that's really related to EditorControls, but better to not add more changes to it if you can avoid it. It's pending an update https://github.com/aframevr/aframe-inspector/pull/687

**Comment by vincentfretin** [comment]
PR worked on is #626
