### ISSUE TITLE
basic billing flow

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#625]

**Comment by rahulkgupta** [comment]
disable "checkout stripe" button on click and show loading when the button is clicked

**Comment by rahulkgupta** [comment]
https://docs.stripe.com/checkout/quickstart

need to use success URL

**Comment by rahulkgupta** [comment]
- loading
- improve success functionality
- add cancel functionality

if user has pro, show manage billing and hide subscribe.
upon success show some congrats modal.
add posthog events

**Comment by kfarr** [comment]
things during test:
- clicking manage sub link needs a loading state
- note: adjusting user claims manually in DB to give pro access is dangerous -- it messes up the billing state assumptions with stripe
