### ISSUE TITLE
AR optimized gltf Export

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#627]
this should be an additional option, separate from

temporarily remove / hide these elements from the scene, then re-add / reshow them:
* skybox
* geospatial layers
* light
* ground under street and blocks grounds
* buildings?

**Comment by vincentfretin** [comment]
Currently with GLTFExporter, you end up with duplicated textures, so consuming more GPU memory. You can check that with https://gltf.report/
I'm using
```
gltf-transform optimize --simplify false scene.glb scene_opt.glb
```
to have the glb optimized, the optimize command includes the dedup step that dedup the materials and so the textures.
We should be able to execute that step in javascript just after GLTFExporter.

**Comment by kfarr** [comment]
see https://github.com/3DStreet/3dstreet/issues/922
