### ISSUE TITLE
use a "drop cursor" with add entity panel

### ISSUE THREAD

**Issue by rahulkgupta** [3DStreet/3dstreet#630]
As a user selecting an object to place from the add entity panel, I don't want to place something right away when I click on a particular model or entity. Instead, it should drop a movable and positionable entity cursor and then place the object after I click again.

The user flow would be something like this:

1. click on a panel card
2. yellow cursor indicating where the drop zone is 
3. click again then the object is placed at the yellow cursor

Other questions:
* If click on a different card, still yellow cursor but the object that will be placed after clicking has changed.
* Hovering over a card in the panel -- do we want to show an object? not at the moment, let's try without that
* yellow pulsating cursor for placement identical to AR

**Comment by vincentfretin** [comment]
With the recent developments, is this addressed or do we need to change something @kfarr?

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/746
