### ISSUE TITLE
Update move action to use 5 finger hand

### ISSUE THREAD

**Issue by rahulkgupta** [3DStreet/3dstreet#634]
update from pointer to 5 hand

**Comment by vincentfretin** [comment]
The icon is correct, so you mean the mouse cursor right?

**Comment by vincentfretin** [comment]
The cursor style is defined in
https://github.com/aframevr/aframe/blob/9436d4b5c555cb924c3f1d5fdf977b5f0a7624e2/src/style/aframe.css#L56-L64

**Comment by rahulkgupta** [comment]
![Screenshot 2024-06-14 at 11 15 15 AM](https://github.com/3DStreet/3dstreet/assets/610372/81e3f2bf-9abc-4b77-a0ca-dfd6cf2b5ba6)

i mean this
