### ISSUE TITLE
UI. The scene graph does not display arrow collapse/expand

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#643]
In the dev repository, the scene graph does not display arrow collapse/expand to the right of entity names, allowing child nodes to be expanded.
![image](https://github.com/3DStreet/3dstreet/assets/32197767/cc97dd35-873b-4dcf-94cb-9d71dff89e4a)
In 3dStreet.app:
![image](https://github.com/3DStreet/3dstreet/assets/32197767/6bdee657-fd81-42f3-a110-5cb6b67b73cb)

**Comment by vincentfretin** [comment]
Good catch, I missed that. I removed the fontawesome cdn in https://github.com/3DStreet/3dstreet/pull/626/files#diff-89952a07bd7e8ca20b2776910a5455132e353d1c486f6721cf3f4829bd185101L26

I fixed the issue in #644
