### ISSUE TITLE
error when first placing 3dtiles

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#661]
how to reproduce:
- create / open a scene with no geo layers
- set a location (long / lat / elevation)
- open the add entity panel
- click on google 3d tiles
- look at console to see error

workaround:
- save scene and reload
- 
```
three.module.js:747 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at si.copy (three.module.js:747:14)
    at Object.update (40f628f5b4d897919e99.js:2:415230)
    at n.tick (40f628f5b4d897919e99.js:2:399534)
    at v.tick (a-scene.js:701:30)
    at v.render (a-scene.js:747:32)
    at bind.js:12:17
    at three.module.js:30226:36
    at r (three.module.js:13400:3)
```

**Comment by kfarr** [comment]
this has happened a few times now, curious if @Algorush you have experienced this or just me?

**Comment by kfarr** [comment]
sometimes this also happens when loading a new scene with 3dtiles

**Comment by Algorush** [comment]
> this has happened a few times now, curious if @Algorush you have experienced this or just me?

yes, I described here: https://github.com/3DStreet/3dstreet/issues/633

**Comment by kfarr** [comment]
@Algorush unfortunately can I ask for help fixing one last thing in the aframe-loader-3dtiles repo?

It is unclear what is happening on line 53 in index.js with both a && and || operator. Here is the raw linting error. Can you update and indicate what is the intended logic with parentheses?
```
/Users/kieranfarr/dev/aframe-loader-3dtiles-component/index.js
  158:23  error  Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations  no-mixed-operators
  158:41  error  Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations  no-mixed-operators
```

**Comment by Algorush** [comment]
> It is unclear what is happening on line 53 in index.js with both a && and || operator. Here is the raw linting error. Can you update and indicate what is the intended logic with parentheses?

Yes, only this is on line 158. The logic is as follows: if `lat` and `long` are passed to the component and/or `height` is passed, then update the coordinates in runtime. May need to enclose `this.data.lat && this.data.long` in parentheses?


> also should this be merged too? or closed?
> [3DStreet/aframe-loader-3dtiles-component#10](https://github.com/3DStreet/aframe-loader-3dtiles-component/pull/10)

It should be merged, to remove extra unnecessary code

**Comment by kfarr** [comment]
close by https://github.com/3DStreet/3dstreet/pull/663
