### ISSUE TITLE
cannot change title after opening scene from another user before I save

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#662]
to reproduce:
* login
* open another user's scene with OLD TITLE
* change the title to NEW TITLE -- observe error notice
* "save as..." the scene
* note that the title has returned to OLD TITLE after saving

instead:
- if auth'ed but not owner of scene, allow changing of scene title on client but do not attempt to save on server

**Comment by Algorush** [comment]
> * if auth'ed but not owner of scene, allow changing of scene title on client but do not attempt to save on server

And if the user changed the title on the client, then if he saves his version of the scene in the cloud or in JSON, the scene should be saved with new title?

**Comment by kfarr** [comment]
looks good!
