### ISSUE TITLE
saving and reloading a scene makes streetmix / street component properties not visible

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#673]
to reproduce:

create new scene
import streetmix
save scene
reload app
load scene
select parent
empty properties panel beneath position/rotation/scale

![image](https://github.com/3DStreet/3dstreet/assets/470477/9221bbec-e2df-4e92-87ad-4bca71a3efa0)

**Comment by Algorush** [comment]
It was resolved in this PR: https://github.com/3DStreet/3dstreet/pull/512

**Comment by kfarr** [comment]
Thanks @Algorush can you rebase that PR (merge the latest changes from main) and ask @vincentfretin to review?

**Comment by Algorush** [comment]
> Thanks @Algorush can you rebase that PR (merge the latest changes from main) and ask @vincentfretin to review?

yes, of course. Wanted to say same

**Comment by Algorush** [comment]
Can I add the public folder to the `.eslintignore` file? Otherwise, when I try to merge from main to the old branch (https://github.com/3DStreet/3dstreet/pull/512), I get lint errors related to the contents of this folder. Or I can make the corrections that linter warns about

**Comment by vincentfretin** [comment]
I don't understand why you have warnings from public folder, the lint command is only checking the src folder.
Oh got it, the commit hook is checking the js and jsx files everywhere. You can just ignore the commit hook while you merge by adding the ` --no-verify` to the command.
`git merge main --no-verify`

**Comment by vincentfretin** [comment]
But yeah you can add
```
dist
public
```

to `.eslintignore` and commit, that should fix it and it won't hurt anyone else in the future.

**Comment by kfarr** [comment]
@vincentfretin @Algorush yes we also added `public` to eslintignore in billing branch for the same reason

**Comment by kfarr** [comment]
closed by #512
