### ISSUE TITLE
Record canvas in posthog

### ISSUE THREAD

**Issue by rahulkgupta** [3DStreet/3dstreet#691]
Context: https://posthog.com/questions/canvas-recording-not-working

From Vincent: You would need a custom aframe build to test that. preserveDrawingBuffer is an option for WebGLRenderer, you can add it here https://github.com/aframevr/aframe/blob/ca7b02ddd7bfa9d606cbbe7b092eb0c08afe5728/src/core/scene/a-scene.js#L618

**Comment by kfarr** [comment]
- download aframe 1.5 tag
- modify the build under context preserve drawing buffer (see Vincent's link above)
- build it and try it?

will monkeypatch like raytracing work?
- no, that was just for the render function, not the creation of the webgl renderer

**Comment by rahulkgupta** [comment]
> * download aframe 1.5 tag
> * modify the build under context preserve drawing buffer (see Vincent's link above)
> * build it and try it?
> 
> will monkeypatch like raytracing work?
> 
> * no, that was just for the render function, not the creation of the webgl renderer

should we do this by forking a-frame repo? I'm eager to get this fixed

**Comment by vincentfretin** [comment]
Yes fork it, create a branch, make a quick change, create a build and copy it locally to 3dstreet repo and reference it in index.html
If that works, make a PR to a aframe with a better change adding an option to the renderer so that we don't leave forever with a fork.

**Comment by rahulkgupta** [comment]
hmm i dont think it worked. Tried it in https://github.com/rahulkgupta/aframe/tree/preservedrawingbuffer 
1. updated `src/core/scene/a-scene.js`
2. ran `npm build dist`
3. copied aframe-master.min.js to 3dstreet repo
4. referenced it in webpack config. https://github.com/3DStreet/3dstreet/pull/871

**Comment by vincentfretin** [comment]
I don't see any commit in your branch, can you push the change you made?

**Comment by rahulkgupta** [comment]
updated, https://github.com/aframevr/aframe/compare/master...rahulkgupta:aframe:preservedrawingbuffer?expand=1

**Comment by vincentfretin** [comment]
Thanks.
Did you deployed to staging environment? Do you have posthog for the staging environment to see one of the video capture? It's still black?
I don't think we have sessions send to posthog for local environment, right?

**Comment by rahulkgupta** [comment]
i updated posthog to capture local development. speaking of which, i should probably turn that off now

**Comment by vincentfretin** [comment]
I commented on
https://posthog.com/docs/session-replay/canvas-recording
`preserveDrawingBuffer` `false` or `true` doesn't change anything. Also `canvas.toDataURL()` give a correct image with or without it, it's just the recording that doesn't show it. The canvas is inside the a-scene element that is a web component seems to be the issue. If I move the canvas outside of it, the canvas is recorded properly. Just typing in the console: `document.body.appendChild(document.querySelector("canvas.a-canvas"))`
so we'll use that hack.

**Comment by vincentfretin** [comment]
Fixed by #952
