### ISSUE TITLE
Support Multiple Streetmix "Sections"

### ISSUE THREAD

**Issue by awjreynolds** [3DStreet/3dstreet#7]
Amazing piece of work. I would like to be able to glue a series of Streetmix together to create a 3D scape. Allowing me to show a bus stop bypass or a narrow section of a road.

**Comment by kfarr** [comment]
Hi @awjreynolds yes this is a great idea and something we've heard from others.

To start tackling this issue, here are a number of questions to start the thought process. No need to answer them yourself but if you have ideas and opinions we welcome your feedback too!

Discussion points to consider:
- How should a user identify and manipulate these street sections?
- Should there be multiple URL text fields for the street sections?
- How many sections should be renderable in one scene?
- How does one specify the ordering and length of each of these sections?
- Is the primary UI/UX for this in the DOM (2d) or within the scene (3D) and if the latter is it intended for desktop (3d + mouse) or in VR use?
- How should transitions (between sections) be handled? Should we assume that there is no transition and that if a transition is needed it would be yet another streetmix section?
- How should movement of animated vehicles be affected by multiple sections?
- Should a compilation of multiple streetmix sections be shareable? What is the URL structure for sharing these? Currently Streetmix3d has no storage and it simply renders what is in the URL. Will there need to be additional DB storage to allow for storing a collection of more than 1 Streetmix URLs?

**Comment by kfarr** [comment]
This feature is now (sort of) possible with manual work, if you create separate streetmix streets for each configuration. Here is an example of a scene with 2 separate streetmix streets loaded: https://github.com/kfarr/3dstreet/blob/master/examples/intersection-simple.html

Issues that remain and other discussion points:
- The length of a street is not yet configurable, it is still 150m in all cases
- Not sure what is the correct "interchange" format to define changes to a street "segment" (or a "slice"). Opened ticket for clarification https://github.com/d-wasserman/shared-row/issues/10

**Comment by kfarr** [comment]
Thanks @awjreynolds for suggesting this feature 1.5 years ago!

Since then, it is now possible to:
- have multiple street "sections" in the same scene
- define the length of each section in meters

Here's an example of a scene with 3 different streetmix street "sections":
https://glitch.com/~aframe-curve-camera-scroll

Marking as closed for now. Feel free to re-open or create new issues if needed
