### ISSUE TITLE
regression - 3dtiles error in ortho mode

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#713]
in updating three-loader-tiles I clobbered @Algorush updates to support ortho mode
there is now a fatal error (react app freezes) when attempting to use ortho camera and 3d tiles at the same time

> But the fact is that that version does not support ortho camera, unlike the version from 3dstreet/three-loader-3dtiles. Therefore, now when switching to Plan View, the old error appears. Just warned you. It's better to add new changes to 3dstreet/three-loader-3dtiles and require this version in the aframe component. Or do I need to make changes related to ortho camera in loaders.gl, I still can’t get around to it

**Comment by vincentfretin** [comment]
close?

**Comment by kfarr** [comment]
yes resolved
