### ISSUE TITLE
add image layer

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#714]
turn this:
https://www.3dstreet.org/docs/development/alpha-labs/#add-an-image

into a built-in component that I can add in add-layer

paid user requesting, this had been assigned in the past but not completed

**Comment by vincentfretin** [comment]
FYI I also need to create an image component for gltf-model-plus to support importing images from a hubs scene https://github.com/c-frame/aframe-gltf-model-plus/issues/13

**Comment by kfarr** [comment]
@vincentfretin yes, aspect ratio is the most annoying thing that has prevented me from doing this very quickly, it looks like that is a very similar request.
