### ISSUE TITLE
pin `maps` property to the top of right-hand properties panel for geospatial layer

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#743]
as a user I want to be able to choose from the map options at the top of the right-hand panel

nice to have:
- the dropdown menu for the 3 map types should have images to represent them
- transform controls not visible (position/rotation/scale)
- button to open geomodal to change location
- display other geospatial fields below `maps` dropdown and geomodal button

**Comment by kfarr** [comment]
@rahulkgupta 

changes I observe:
old:


new:

click on geo layer, if no location set yet:
![Image](https://github.com/user-attachments/assets/2d254b2c-1b20-4c36-9163-fd80d9272ec7)

after setting location:
![Image](https://github.com/user-attachments/assets/69f6d727-9d28-4835-984c-41454d808bb8)

after setting location, and click "show advanced"
![Image](https://github.com/user-attachments/assets/0345a846-22ac-448a-a2ae-357fb00f2625)

Env panel:
![Image](https://github.com/user-attachments/assets/405aee6a-7ac9-447c-b8bc-1c138ab125ad)




future improvements:
- "Environment" layer should show preset and background color as top fields, should not need to click "show advanced" -- most urgent
- On geo panel, with a location set and "show advanced" the "set location" -- can wait

**Comment by rahulkgupta** [comment]
im not sure about the last task list item. i think for the first, we can create a separate ticket to tackle.

**Comment by vincentfretin** [comment]
For the third point, hide the Map Source select field when you click on Show Advanced, or omit the Maps select field in advanced fields.
