### ISSUE TITLE
zoom and camera reset buttons stopped working

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#745]
testing on chrome / safari on 3dstreet.app

**Comment by vincentfretin** [comment]
It works for me.
Do you still reproduce? Do you have an error in the console?

**Comment by kfarr** [comment]
@vincentfretin cannot reproduce

**Comment by kfarr** [comment]
@vincentfretin i can reproduce but not reliably. it happens when i'm working on a scene for a while and most need it because the camera is kinda message up (like too zoomed-in to the wrong area). there is no console error. is there a good way to debug this?

**Comment by vincentfretin** [comment]
Currently if you go in viewer mode and back, the reset zoom button isn't working anymore. That's probably your issue?

**Comment by vincentfretin** [comment]
The code to bind the event listeners to the buttons needs to be rewritten in React really, I find it strange to create the button in React but bind the listeners in vanilla js here. When the ZoomButtons React component unmount and remount, that's what is happening here when you go the viewer mode and back, the new created buttons doesn't have the listeners binded to them. That's the issue.

**Comment by kfarr** [comment]
* add listener / remove listener resetZoom Button etc. is in the EditorControls
* Instead should be in zoom buttons
* are editor controls exposed in global from react component? somehow make that happen
