### ISSUE TITLE
drag and drop pro layer doesn't work on production

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#757]
I think it's because function names were clobbered during minimization so they cannot be fired after the drag event by using the function name as string

console error is:
`AddLayerPanel.component.jsx:412 Function $V not found
onDrop	@	`

So ... maybe there is a way to mark those functions to not be minimized?

**Comment by vincentfretin** [comment]
If we add a new function, we need to make sure to add it in the webpack config as well, it's a bit brittle.
I'm wondering if there is another way to modify the code to avoid having a name mismatch when it's minified.

**Comment by kfarr** [comment]
I think we could add a key value to the function name that won't be
minified? Or a lookup table with a string lookup key that won't be minified?
