### ISSUE TITLE
(p) allow user to set clipping box on google 3d tiles

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#758]
https://github.com/nytimes/three-loader-3dtiles/issues/165

**Comment by kfarr** [comment]
progress so far: https://github.com/3DStreet/aframe-loader-3dtiles-component/pull/14

**Comment by kfarr** [comment]
Linked the branch WIP to this ticket. Barely works, steps before it's "ready" would be:
- right now this only works to crop AABB but not OBB. see image 
- instead of clip-box object, default selector of `[data-layer-name="Underground"]` which would return one matching underground box for a street if it exists in the scene, at least for a v1 this ok but we may want a better way to better define clipping areas in the future. perhaps allowing as user to select a street and it may be easier to make the clipping planes from scratch based on street component's length and width, the street entity's position and rotation.
- default clippingEnabled should be false and remove the clip-box from scene

![Image](https://github.com/user-attachments/assets/fc0988c3-d459-4b69-9346-1bef71db6766)

**Comment by kfarr** [comment]
@vincentfretin curious if you have any quick idea to advise on this AABB vs. OBB issue... ^^

**Comment by vincentfretin** [comment]
I don't see any rotation applied to your clipPlanes THREE.Plane. Did you try setting clipPlane.rotation.y for each of your plane for example?

**Comment by kfarr** [comment]
try this:
https://github.com/aframevr/aframe/blob/master/src/components/obb-collider.js

example:
https://glitch.com/edit/#!/ritzy-coral-sense?path=index.html%3A1%3A0

**Comment by kfarr** [comment]
@vincentfretin would you be willing to try to help with this?

Some notes:
- This was code that was made with me and Claude using Cursor, so it is not great. It works OK but is axis aligned bounding box and doesn't look good.
- I could use help with how to get this to work on any angle, not just aligned with the bounding box
- I did find that using OBB component with debugging on will create the desired box that we want
- It could be that we rewrite this using a modified version of the OBB component debug box, and then set the clipping planes based on this debug box

Any other ideas?

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/882
