### ISSUE TITLE
regression - streetplan site not loading

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#761]
https://3dstreet.app/#https://streetplan.net/3dstreet/86591

**Comment by vincentfretin** [comment]
Do you have some lead where we need to investigate? Is it the streetplan-loader component that takes care of loading the json from the hash url here?

**Comment by kfarr** [comment]
see this PR: https://github.com/3DStreet/3dstreet/issues/498#issue-2176961598

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/commit/727d5551900c8f9803de35da3356ae9ba5c4dd6c
