### ISSUE TITLE
default google 3d tiles not shown in scenegraph after setting location

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#770]
after adding 3dtiles, somehow we needs to fire another entitychanged or whatever scenegraph update event needed

the tiles are added how? i think in the modal maybe after the update button is pressed?

**Comment by vincentfretin** [comment]
I'm not sure if this is this one, but the `onSaveHandler` in GeoModal here
https://github.com/3DStreet/3dstreet/blob/a7dbaca9db29b71ff6e10fc44b740ecad34a761e/src/editor/components/modals/GeoModal/GeoModal.component.jsx#L144-L154
should definitely be rewritten to use `EntityUpdateCommand` similar to https://github.com/3DStreet/3dstreet/pull/789/files#diff-a70d189aca39070b7c4bd36206c8df559633374a33865caf6616323d1e403e4cR49 after the following PR is merged.
- #788

**Comment by vincentfretin** [comment]
I did the above change in #789 but that was not the issue. I did fix it in https://github.com/3DStreet/3dstreet/pull/789/commits/69904017a9557f80e0881f8bb641fd655c50d28e though.
