### ISSUE TITLE
ui scroll issue in right-hand panel cannot select bottom-most property

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#776]
there is another property value that is not visible in the right-hand panel:

![Image](https://github.com/user-attachments/assets/433c7914-559a-4c98-9d7d-c804e620e171)

**Comment by vincentfretin** [comment]
That's a regression from my change https://github.com/3DStreet/3dstreet/commit/681181cb0752022299e868f14d6423815b2ddac7 I'll take a look.
