### ISSUE TITLE
save layer visibility state, layer visibility should be undo-able

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#793]
As a user who hides a layer using the scene-graph panel layer checkbox, I expect the layer that I have hidden to remain hidden upon opening the scene again in a later session.

Also, hiding / showing layers via the scene-graph panel should be a undo/redo-able action

**Comment by vincentfretin** [comment]
The undoable part is fixed in #820 
For saving the visible component, not sure where the issue is. I'm starring at json-utils, nothing caught my eyes.

**Comment by kfarr** [comment]
Is visibility treated like a component named `visible` with a single value of `true` or `false`? That is different than material.visibility under the hood? Or the same thing?

Looking at the json of a saved scene, we are not saving `visible`. It might be something to explicitly support in a whitelist somewhere

**Comment by vincentfretin** [comment]
It should be a `visible` component yes. The `visible` component modify `el.object3D.visible`, so nothing to do with material.

**Comment by kfarr** [comment]
closed by #820
