### ISSUE TITLE
(wb/cam) double-click entity to center camera in scenegraph should also apply to viewport double click

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#797]
upon double clicking the object is selected and the camera is placed at a distance relative to the size of the bounding box of the selected object, including a y (height)

**Comment by vincentfretin** [comment]
You disabled the dblclick behavior long time ago, I think mainly because of #710 that we fixed now, so you can compare viewport.js with the one from aframe-inspector to get back the behavior. There is still the y position issue though.
