### ISSUE TITLE
(wb) new models: bus shelter alt1, motorbike user, tuk tuk

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#803]
bus shelter: slanted roof, bench underneath, concrete, metal
motorbike user: with integrated character

![Image](https://github.com/user-attachments/assets/833460b4-6167-483c-b780-29b9b19c4284)

https://www.mapillary.com/app/?lat=1.354509799999974&lng=173.04195470000002&z=19.9&focus=photo&pKey=1272976553615315&x=0.4449056308529537&y=0.5438597191738017&zoom=2.0730337078651675

examples of tuk tuks in target region

![Image](https://github.com/user-attachments/assets/dddc9e24-2850-4c5c-9d02-62b8aa2b458c)

https://github.com/orgs/3DStreet/projects/5/views/1?pane=issue&itemId=77447566

**Comment by kfarr** [comment]
@gnansai there is a request for 1 more object, a typical minibus found in India or Africa. Do you have reference images for this since it is in your locale, or would you like me to find some reference images?

**Comment by gnansai** [comment]
@kfarr , I don't have any but I can find online.  
If find any reference image that you prefer, do share.

**Comment by gnansai** [comment]
@kfarr 
Here is an update of bus-shelter-alt-1

https://github.com/gnansai/3dstreet-assets-dist/tree/main/sets/bus-shelter-alt-1/gltf-exports/draco

![image](https://github.com/user-attachments/assets/660a8340-8cdb-47e4-9707-838c6e4ef9d9)
![image](https://github.com/user-attachments/assets/c17312ff-9ffc-4580-a439-4e03f6749ade)
![image](https://github.com/user-attachments/assets/22dec18b-8c3f-4cf8-b6d1-c67b308d56cd)

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update of tuk tuk. I have not rigged the wheels yet.

https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/tuk-tuk.glb

![image](https://github.com/user-attachments/assets/b60e5c07-9c47-40c4-930f-e85d964a8b40)
![image](https://github.com/user-attachments/assets/a34cc521-4fcf-46fa-8bda-e733226cf25e)
![image](https://github.com/user-attachments/assets/137da90b-c88d-4348-93af-7ae9f0148371)

**Comment by gnansai** [comment]
Hi @kfarr 
Could you share any specific references for the bike and the mini bus?

**Comment by kfarr** [comment]
@gnansai thanks the tuk tuk and shelter look great

for bike, here is are 2 images (front/back) taken of 2 motorbike riders from a target region. The bikes aren't exactly the same but you can use whatever prominent features from either that you choose:
front:
![image](https://github.com/user-attachments/assets/ccd75288-1897-4c93-a37b-a2d75f976073)
back:
![image](https://github.com/user-attachments/assets/f211a3f3-db1b-435a-b5ff-ad808e00f4e4)

for minibus

**Comment by gnansai** [comment]
Hi @kfarr 
Here is an update of two wheeler with person
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/two-wheeler-with-person.glb

![image](https://github.com/user-attachments/assets/cb485e90-1f34-42de-b87e-edf158fd10d9)
![image](https://github.com/user-attachments/assets/5e6c7103-5e92-4439-a941-37a178bc528d)
![image](https://github.com/user-attachments/assets/3b1ace2f-e780-4daa-8dad-c2ee020740bf)
![image](https://github.com/user-attachments/assets/61d6a353-076f-417d-bab5-d94e3dfd5018)

**Comment by kfarr** [comment]
@gnansai looks great! last request, can you make the person's skin darker?

**Comment by gnansai** [comment]
@kfarr I made the skin dark
![image](https://github.com/user-attachments/assets/a6c67113-0359-4ee0-a976-ad4781def66c)

**Comment by gnansai** [comment]
@kfarr Here is an update of mini bus
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/vehicles/gltf-exports/draco/mini-bus.glb
![image](https://github.com/user-attachments/assets/07882c2f-7caa-474c-97ce-68facb223acc)
![image](https://github.com/user-attachments/assets/0d33ee07-10e2-467d-8fdc-9f596609d2bc)
![image](https://github.com/user-attachments/assets/0283bae0-b62d-4286-ba36-27a27401c7a1)

**Comment by kfarr** [comment]
all together:
![Image](https://github.com/user-attachments/assets/9df1a250-da2b-4d38-862b-e75477cb5474)

**Comment by kfarr** [comment]
closed by #849
