### ISSUE TITLE
(patricio) ability to choose move vs. rotate on toolbar instead of `e` and `w` keys

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#811]
current toolbar:
![Image](https://github.com/user-attachments/assets/aa8e5ec8-f71b-40c9-be95-24b1cbedece0)

proposed toolbar:
![Image](https://github.com/user-attachments/assets/c8085f40-a0f2-4637-b942-dcdb93fb37ac)

changes:
- new order, grab icon is left-most
- new icons rotate and move instead of "pointer" icon
- default tool should still be "move" as it is today (previously "pointer"), shown highlighted above in "proposed toolbar" image
- pressing the rotate icon should be same behavior as pressing `e`. If `e` key is pressed, the toolbar should show the rotate tool selected state
- pressing the move icon should be same behavior as pressing `w`. If `w` key is pressed, the toolbar should show the move tool selected state

future task / nice to haves:
- change the cursor itself to reflect match the change in mode from move, rotate, etc. (future cursor ideas below)
- the `h` key could be bound to hand since it is no longer used for help

future cursor ideas:
![Image](https://github.com/user-attachments/assets/9cb5d496-3783-4ed8-a8d2-94ca4660b212)

**Comment by vincentfretin** [comment]
The cursor can only be the one from css cursor property, see https://tailwindcss.com/docs/cursor you can hover on the different lines to see your OS themed cursor.
Unless you really want to use css `cursor: none;` and use your own image that follows the cursor, but I'm sure there are some edge cases to handle if you do that.

**Comment by vincentfretin** [comment]
Some code that you will need in `src/editor/components/components/ActionBar/ActionBar.component.jsx`:
```js
    const [transformMode, setTransformMode] = useState("translate"); // "translate" | "rotate" | "scale"
    useEffect(() => {
      // e (rotate) and w (translate) shortcuts
      const onChange = (mode) => {
        setTransformMode(mode);
      }
      Events.on("transformmodechange", onChange);
      return () => {
        Events.off("transformmodechange", onChange);
      }
    }, [])
    
    const changeTransformMode = (mode) => { // mode: "translate" | "rotate" | "scale"
      Events.emit("transformmodechange", mode);
    }

    // on buttons
   onClick={() => changeTransformMode("translate")}
   onClick={() => changeTransformMode("rotate")}
```
