### ISSUE TITLE
(wb/cam) transform control bug fixing - don't display in "grab" mode, sizing incorrect

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#812]
Issue1: As a user traveling to show points of interest by double-clicking on layers, I do not want the transform controls to appear when the "grab" tool is selected and I double-click on a layer.

Issue2: Further, if I am using the "move" or "rotate" tool I want the transform controls to appear on the newly selected (double-clicked) object, however I do not want them to be huge after the camera moves to the newly selected object.

Diagnosis on issue 2
- when the transform controls are created for a newly selected object, it appears to use the "screen space" to determine the size of the controls to ensure consistency between object selection (see capture1)
- when the camera moves after the transform controls are created, they will appear larger the further away the newly selected object is from the previous camera location. For example the next nearest objects (see capture2 below) and (see capture3 below)

capture1:
![Image](https://github.com/user-attachments/assets/8435507a-8b0d-4574-a34e-ea8543c88b2e)

capture2:
![Image](https://github.com/user-attachments/assets/9e87cdb8-c8f8-4a57-8a96-084d5a6699f7)

capture3:
![Image](https://github.com/user-attachments/assets/eb67e0a3-a08d-435f-875d-0add65a576c0)

Idea for alternative behavior for issue 2:
- instead, perhaps the transform controls can be resized in realtime depending on the screenspace size as it varies during camera transitions?

**Comment by vincentfretin** [comment]
For issue2, this was reported in aframe-inspector as well https://github.com/aframevr/aframe-inspector/issues/649

**Comment by vincentfretin** [comment]
PR #818 fixes the two issues
