### ISSUE TITLE
use new bollard instead of safehit

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#824]
add a new model node name for bollard, keep safehit for legacy reasons as to not break old scenes, update streetmix parser logic to use bollard instead of safehit model

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L1164

change from safehit to bollard after object updated

**Comment by gnansai** [comment]
Hi @kfarr 
here is the updated glb file
I have
1. reduced the height of bollard to 2/3
2. add the old model as safehit
https://github.com/gnansai/3dstreet-assets-dist/blob/main/sets/dividers/gltf-exports/draco/dividers.glb

![image](https://github.com/user-attachments/assets/38a6d5cc-73b6-4c38-8400-7c2826346160)
![image](https://github.com/user-attachments/assets/16e91275-c0db-4129-ad2c-a6e3485aef12)
