### ISSUE TITLE
(p) allow access by domain

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#833]
As a user logging in with an email address domain name that matches a specified customer's domain name, grant Pro access.

Implementation ideas:
- could there be a stripe transaction that specifies the domain to be whitelisted?
- is there a new database table for organizations with display name, domain name, primary user, plan, and stripe transaction information?
- add additional logic in `isUserPro` (api/user.js) to check the user's email domain for the org whitelist

**Comment by rahulkgupta** [comment]
#835

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/835
