### ISSUE TITLE
Be able to remove the street-geo component

### ISSUE THREAD

**Issue by vincentfretin** [3DStreet/3dstreet#854]
As far as I can see, there is no way to remove the component currently.
We can probably change the geo modal to remove the location entirely and so remove the street-geo component? What do you think?

**Comment by kfarr** [comment]
@vincentfretin yes user will definitely want to remove the tiles. perhaps an alternative that fits the UI is to add a map option for 'none'

**Comment by vincentfretin** [comment]
'none' is fine, so you don't lose the geolocation if you want to enable it again

**Comment by kfarr** [comment]
closed by #904
