### ISSUE TITLE
Creating thumbnails for the standalone glb models

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#870]
Links to the branches:
- https://github.com/3DStreet/3dstreet-assets-dist/tree/thumbnail-maker
- https://github.com/3DStreet/3dstreet/tree/model-card-previews

**Comment by rahulkgupta** [comment]
https://github.com/3DStreet/3dstreet/pull/873
https://github.com/3DStreet/3dstreet-assets-dist/pull/32

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/888
