### ISSUE TITLE
`enableClipping` slows down app

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#884]
When setting "enableClipping" true on geospatial layers you can notice stuttering or "jumping" in the UI and camera movement when zooming or double-clicking on an object.

The stuttering appears to match the 250s throttled tick in the new obb-clipping component. traversing all the tiles to apply the clipping planes is a super expensive operation. perhaps we could store the previous values and only apply traverse to apply clipping planes if the previous values actually changed?

Also, in addition to monitoring for pose changes on target object, we can monitor for tiles loaded events from 3dtiles runtime object via threejs-loader-tiles library, see: https://github.com/nytimes/three-loader-3dtiles/issues/165#issuecomment-2134763490

**Comment by rahulkgupta** [comment]
Diego had some good points in https://github.com/3DStreet/3dstreet/pull/882#pullrequestreview-2341502216 that might resolve this

**Comment by kfarr** [comment]
Re: Diego's comments:
- Yes we should only update planes & apply on matrix movements, same as bounding box calc
- However, the 3dtiles are constantly updating from perspective and LOD changes, if we don't apply planes every tick, there will be new tiles that pop in without the clipping planes applied  
- An alternative to checking every tick, we can hook into contentPostProcess event [1] that is emitted from the 3dtiles
- This is modified in the aframe-3dtiles-component repo -- i just finished this here: https://github.com/3DStreet/aframe-loader-3dtiles-component/commit/339b735f6a454c1b6a8f823b1f0904f9ddb6b2d9#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

Changes to obb-clipping component (or as new component):
- apply clipping planes to the returned mesh of the new tiles upon emitting 'contentPostProcess
- instead of traversing the entire tree just apply the clipping planes to that

[1] https://github.com/nytimes/three-loader-3dtiles/blob/dev/docs/three-loader-3dtiles.loaderoptions.contentpostprocess.md

**Comment by kfarr** [comment]
closed by #887 887
