### ISSUE TITLE
top level layers should not allow transformation

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#886]
suggestion to create a new data attribute "data-no-transform" whose existence on an entity shall indicate:
- no transform controls should display to the end-user (no transform helpers for move, scale, rotate)
- in the right-hand panel, vec3 values should be read only / disable

the attribute `data-no-transform` or `data-read-only` should be applied to:
* “user layers”, “geospatial layers” and “street segment container”
* also "viewer" and "environment"

why:
as a user, if I update these layers it results in unintended outcomes, such as incorrect clipping area

![image](https://github.com/user-attachments/assets/dc89a050-0dec-4500-89fc-844567b213a2)

**Comment by rahulkgupta** [comment]
for user layers and street segment container, there shouldn't be a right panel either AFAICT. Whereas, for geospatial, there should be. I would argue hiding the viewer layer from the layers panel. Environment should stay for now, but would be a good thing to move to photo mode down the line

**Comment by rahulkgupta** [comment]
This could also be a good time to combine the geospatial layers in the layers panel and the globe icon

**Comment by rahulkgupta** [comment]
I was playing around w/ v0 and it made this which is quite solid! https://v0.dev/chat/0vnKOGDd1n2?b=b_tTKCDnksAqU
