### ISSUE TITLE
Link to demo URL broken

### ISSUE THREAD

**Issue by kevincannon** [3DStreet/3dstreet#94]
In the description it links to this URL, but that's broken now.

https://kfarr.github.io/3dstreet/

**Comment by kfarr** [comment]
thanks fixed the link I found on the [README quickstart](https://github.com/3DStreet/3dstreet#quick-start---how-to-make-your-own-3d-street) as well a few on https://3d.st. Marking closed but let me know if you find any more that need to be updated.
