### ISSUE TITLE
Still an old openpaymentmodal in AddLayerPanel

### ISSUE THREAD

**Issue by vincentfretin** [3DStreet/3dstreet#942]
Doing a search in the codebase with `grep -r "Events.emit('ope" src/` it seems you missed one @rahulkgupta 
`src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx:      Events.emit('openpaymentmodal');`

**Comment by vincentfretin** [comment]
@rahulkgupta @kfarr Did you see this issue?
https://github.com/3DStreet/3dstreet/blob/b11aa565031d4439f383cb2a71b8e676644f9b20/src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx#L315
needs to be adapted, it won't open any payment modal currently.

**Comment by rahulkgupta** [comment]
https://github.com/3DStreet/3dstreet/pull/945
